from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import httpx
import pytest


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from siglume_api_sdk import (  # noqa: E402
    AppCategory,
    AppManifest,
    ApprovalMode,
    PermissionClass,
    PriceModel,
    SiglumeAPIError,
    SiglumeClient,
    SiglumeClientError,
    ToolManual,
    ToolManualPermissionClass,
)
from siglume_api_sdk.operations import DEFAULT_OPERATION_AGENT_ID  # noqa: E402
from siglume_api_sdk.testing import Recorder, RecordMode  # noqa: E402


def envelope(data, *, trace_id: str = "trc_test", request_id: str = "req_test") -> dict[str, object]:
    return {
        "data": data,
        "meta": {"request_id": request_id, "trace_id": trace_id},
        "error": None,
    }


def build_manifest() -> AppManifest:
    return AppManifest(
        capability_key="price-compare-helper",
        name="Price Compare Helper",
        job_to_be_done="Compare retailer prices for a product and return the best current offer.",
        category=AppCategory.COMMERCE,
        permission_class=PermissionClass.READ_ONLY,
        approval_mode=ApprovalMode.AUTO,
        dry_run_supported=True,
        required_connected_accounts=[],
        price_model=PriceModel.FREE,
        jurisdiction="US",
        short_description="Search multiple retailers and summarize the best current price.",
        example_prompts=["Compare prices for Sony WH-1000XM5."],
    )


def build_tool_manual() -> ToolManual:
    return ToolManual(
        tool_name="price_compare_helper",
        job_to_be_done="Search multiple retailers for a product and return a ranked price comparison the agent can cite.",
        summary_for_model="Looks up current retailer offers and returns a structured comparison with the best deal first.",
        trigger_conditions=[
            "owner asks to compare prices for a product before deciding where to buy",
            "agent needs retailer offer data to support a shopping recommendation",
            "request is to find the cheapest or best-value option for a product query",
        ],
        do_not_use_when=[
            "the request is to complete checkout or place an order instead of comparing offers",
        ],
        permission_class=ToolManualPermissionClass.READ_ONLY,
        dry_run_supported=True,
        requires_connected_accounts=[],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Product name, model number, or search phrase."},
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        output_schema={
            "type": "object",
            "properties": {
                "summary": {"type": "string", "description": "One-line overview of the best available deal."},
                "offers": {"type": "array", "items": {"type": "object"}, "description": "Ranked retailer offers."},
            },
            "required": ["summary", "offers"],
            "additionalProperties": False,
        },
        usage_hints=["Use this tool after the owner has named a product and wants evidence-backed price comparison."],
        result_hints=["Lead with the best offer and then summarize notable trade-offs."],
        error_hints=["If no offers are found, ask for a clearer product name or model number."],
    )


def build_client(handler, *, agent_key: str | None = None) -> SiglumeClient:
    return SiglumeClient(
        api_key="sig_test_key",
        agent_key=agent_key,
        base_url="https://api.example.test/v1",
        transport=httpx.MockTransport(handler),
    )


def test_auto_register_and_confirm_registration_return_typed_objects(tmp_path: Path) -> None:
    manifest = build_manifest()
    tool_manual = build_tool_manual()
    requests: list[tuple[str, str, dict[str, object]]] = []
    cassette_path = tmp_path / "auto_register_recorded.json"

    def handler(request: httpx.Request) -> httpx.Response:
        body = json.loads(request.content.decode("utf-8")) if request.content else {}
        requests.append((request.method, request.url.path, body))
        assert request.headers["Authorization"] == "Bearer sig_test_key"

        if request.url.path == "/v1/market/capabilities/auto-register":
            assert body["capability_key"] == manifest.capability_key
            assert "Registration bootstrap generated by SiglumeClient." in body["source_code"]
            return httpx.Response(
                201,
                json=envelope(
                    {
                        "listing_id": "lst_123",
                        "status": "draft",
                        "auto_manifest": {"capability_key": manifest.capability_key},
                        "confidence": {"overall": 0.94},
                        "review_url": "/owner/publish?listing=lst_123",
                    }
                ),
            )

        if request.url.path == "/v1/market/capabilities/lst_123/confirm-auto-register":
            assert body["approved"] is True
            assert body["overrides"]["tool_manual"]["tool_name"] == tool_manual.tool_name
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "listing_id": "lst_123",
                        "status": "pending_review",
                        "release": {"release_id": "rel_123", "release_status": "pending_review"},
                        "quality": {
                            "overall_score": 84,
                            "grade": "B",
                            "issues": [],
                            "improvement_suggestions": ["Add one more retailer-specific trigger example."],
                        },
                    },
                    trace_id="trc_confirm",
                ),
            )

        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.RECORD) as recorder:
        with recorder.wrap(build_client(handler)) as client:
            receipt = client.auto_register(manifest, tool_manual)
            confirmation = client.confirm_registration(receipt.listing_id)

    def unexpected_handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError(f"Replay should not hit transport: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.REPLAY) as recorder:
        with recorder.wrap(build_client(unexpected_handler)) as client:
            replay_receipt = client.auto_register(manifest, tool_manual)
            replay_confirmation = client.confirm_registration(replay_receipt.listing_id)

    assert receipt.listing_id == "lst_123"
    assert receipt.trace_id == "trc_test"
    assert confirmation.listing_id == "lst_123"
    assert confirmation.status == "pending_review"
    assert confirmation.quality.overall_score == 84
    assert confirmation.quality.grade == "B"
    assert confirmation.trace_id == "trc_confirm"
    assert requests[0][1] == "/v1/market/capabilities/auto-register"
    assert requests[1][1] == "/v1/market/capabilities/lst_123/confirm-auto-register"
    assert replay_receipt.listing_id == receipt.listing_id
    assert replay_confirmation.quality.grade == confirmation.quality.grade


def test_cursor_pages_follow_next_cursor_for_listings_and_usage() -> None:
    call_counter = {"listings": 0, "usage": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/market/capabilities":
            call_counter["listings"] += 1
            if request.url.params.get("cursor") == "next_listing":
                return httpx.Response(
                    200,
                    json=envelope(
                        {
                            "items": [
                                {
                                    "id": "lst_2",
                                    "capability_key": "calendar-sync",
                                    "name": "Calendar Sync",
                                    "status": "published",
                                    "dry_run_supported": True,
                                    "price_model": "free",
                                    "price_value_minor": 0,
                                    "currency": "USD",
                                }
                            ],
                            "next_cursor": None,
                            "limit": 1,
                            "offset": 1,
                        }
                    ),
                )
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "lst_1",
                                "capability_key": "price-compare-helper",
                                "name": "Price Compare Helper",
                                "status": "draft",
                                "dry_run_supported": True,
                                "price_model": "free",
                                "price_value_minor": 0,
                                "currency": "USD",
                            }
                        ],
                        "next_cursor": "next_listing",
                        "limit": 1,
                        "offset": 0,
                    }
                ),
            )

        if request.url.path == "/v1/market/usage":
            call_counter["usage"] += 1
            if request.url.params.get("cursor") == "next_usage":
                return httpx.Response(
                    200,
                    json=envelope(
                        {
                            "items": [
                                {
                                    "id": "use_2",
                                    "capability_key": "price-compare-helper",
                                    "units_consumed": 3,
                                    "outcome": "success",
                                    "execution_kind": "dry_run",
                                    "created_at": "2026-04-19T00:00:00Z",
                                }
                            ],
                            "next_cursor": None,
                            "limit": 1,
                            "offset": 1,
                        }
                    ),
                )
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "use_1",
                                "capability_key": "price-compare-helper",
                                "units_consumed": 1,
                                "outcome": "success",
                                "execution_kind": "dry_run",
                                "created_at": "2026-04-18T00:00:00Z",
                            }
                        ],
                        "next_cursor": "next_usage",
                        "limit": 1,
                        "offset": 0,
                    }
                ),
            )

        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        listings = client.list_my_listings(limit=1)
        usage = client.get_usage(capability_key="price-compare-helper", limit=1)
        listing_items = listings.all_items()
        usage_items = usage.all_items()

    assert [item.capability_key for item in listing_items] == ["price-compare-helper", "calendar-sync"]
    assert [item.units_consumed for item in usage_items] == [1, 3]
    assert call_counter == {"listings": 2, "usage": 2}


def test_account_preferences_and_plan_wrappers_use_direct_me_endpoints() -> None:
    requests: list[tuple[str, str, dict[str, object]]] = []

    def handler(request: httpx.Request) -> httpx.Response:
        body = json.loads(request.content.decode("utf-8")) if request.content else {}
        requests.append((request.method, request.url.path, body))

        if request.url.path == "/v1/me/preferences" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "language": "ja",
                        "summary_depth": "concise",
                        "notification_mode": "daily_digest",
                        "autonomy_level": "review_first",
                        "interest_profile": {"themes": ["ai", "marketplace"]},
                        "consent_policy": {"share_profile": False},
                    }
                ),
            )
        if request.url.path == "/v1/me/preferences" and request.method == "PUT":
            assert body == {
                "language": "en",
                "interest_profile": {"themes": ["ai", "finance"]},
            }
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "language": "en",
                        "summary_depth": "concise",
                        "notification_mode": "daily_digest",
                        "autonomy_level": "review_first",
                        "interest_profile": {"themes": ["ai", "finance"]},
                        "consent_policy": {"share_profile": False},
                    }
                ),
            )
        if request.url.path == "/v1/me/plan":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "plan": "plus",
                        "display_name": "Plus",
                        "limits": {"manifesto_chars": 1000},
                        "available_models": [{"id": "claude-sonnet-4-6", "provider": "anthropic"}],
                        "default_model": "claude-sonnet-4-6",
                        "selected_model": "claude-sonnet-4-6",
                        "subscription_id": "sub_demo_plan",
                        "period_end": "2026-05-20T00:00:00Z",
                        "cancel_scheduled_at": None,
                        "cancel_pending": False,
                        "plan_change_scheduled_to": None,
                        "plan_change_scheduled_at": None,
                        "plan_change_scheduled_currency": None,
                        "usage_today": {"chat": 4},
                        "available_plans": {"plus": {"display_name": "Plus", "price_usd": 1100}},
                    }
                ),
            )
        if request.url.path == "/v1/me/plan/checkout":
            assert request.url.params["plan"] == "plus"
            assert request.url.params["currency"] == "usd"
            return httpx.Response(
                200,
                json=envelope({"checkout_url": "https://billing.example.test/checkout/cs_live_demo"}),
            )
        if request.url.path == "/v1/me/plan/billing-portal":
            return httpx.Response(
                200,
                json=envelope({"portal_url": "https://billing.example.test/portal/bps_live_demo"}),
            )
        if request.url.path == "/v1/me/plan/cancel":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "cancelled": True,
                        "effective_at": "2026-05-20T00:00:00Z",
                        "cancel_scheduled_at": "2026-05-20T00:00:00Z",
                        "plan": "plus",
                        "subscription_id": "sub_demo_plan",
                        "rail": "stripe",
                    }
                ),
            )
        if request.url.path == "/v1/me/plan/web3-mandate":
            assert request.url.params["plan"] == "pro"
            assert request.url.params["currency"] == "jpy"
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "mandate_id": "mand_plan_demo",
                        "payment_mandate_id": "pmd_plan_demo",
                        "network": "polygon",
                        "payee_type": "platform",
                        "payee_ref": "platform:plan:pro",
                        "purpose": "subscription",
                        "cadence": "monthly",
                        "token_symbol": "JPYC",
                        "display_currency": "JPY",
                        "max_amount_minor": 4980,
                        "status": "active",
                        "retry_count": 0,
                        "metadata_jsonb": {"plan": "pro"},
                        "chain_receipt": {
                            "receipt_id": "chr_plan_demo",
                            "tx_hash": "0x" + ("c" * 64),
                            "network": "polygon",
                            "chain_id": 137,
                            "confirmations": 12,
                            "finality_confirmations": 12,
                            "payload": {"amount_minor": 4980},
                        },
                    }
                ),
            )
        if request.url.path == "/v1/me/plan/web3-cancel":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "mandate_id": "mand_plan_demo",
                        "payment_mandate_id": "pmd_plan_demo",
                        "network": "polygon",
                        "payee_type": "platform",
                        "payee_ref": "platform:plan:pro",
                        "purpose": "subscription",
                        "cadence": "monthly",
                        "token_symbol": "JPYC",
                        "display_currency": "JPY",
                        "max_amount_minor": 4980,
                        "status": "cancelled",
                        "retry_count": 1,
                        "metadata_jsonb": {"plan": "pro"},
                    }
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        preferences = client.get_account_preferences()
        updated_preferences = client.update_account_preferences(
            language="en",
            interest_profile={"themes": ["ai", "finance"]},
        )
        plan = client.get_account_plan()
        checkout = client.start_plan_checkout("plus", currency="usd")
        portal = client.open_plan_billing_portal()
        cancellation = client.cancel_account_plan()
        mandate = client.create_plan_web3_mandate("pro", currency="jpy")
        cancelled_mandate = client.cancel_plan_web3_mandate()

    assert preferences.language == "ja"
    assert updated_preferences.language == "en"
    assert updated_preferences.interest_profile == {"themes": ["ai", "finance"]}
    assert plan.plan == "plus"
    assert plan.available_plans["plus"]["price_usd"] == 1100
    assert checkout.checkout_url == "https://billing.example.test/checkout/cs_live_demo"
    assert portal.portal_url == "https://billing.example.test/portal/bps_live_demo"
    assert cancellation.cancelled is True
    assert cancellation.rail == "stripe"
    assert mandate.mandate_id == "mand_plan_demo"
    assert mandate.chain_receipt is not None
    assert mandate.chain_receipt.tx_hash == "0x" + ("c" * 64)
    assert cancelled_mandate.status == "cancelled"
    assert [path for _, path, _ in requests] == [
        "/v1/me/preferences",
        "/v1/me/preferences",
        "/v1/me/plan",
        "/v1/me/plan/checkout",
        "/v1/me/plan/billing-portal",
        "/v1/me/plan/cancel",
        "/v1/me/plan/web3-mandate",
        "/v1/me/plan/web3-cancel",
    ]


def test_update_account_preferences_requires_at_least_one_field() -> None:
    with build_client(lambda request: httpx.Response(500)) as client:
        with pytest.raises(SiglumeClientError, match="requires at least one preference field"):
            client.update_account_preferences()


def test_start_plan_checkout_requires_target_tier() -> None:
    with build_client(lambda request: httpx.Response(500)) as client:
        with pytest.raises(SiglumeClientError, match="target_tier is required"):
            client.start_plan_checkout("")


def test_create_plan_web3_mandate_requires_target_tier() -> None:
    with build_client(lambda request: httpx.Response(500)) as client:
        with pytest.raises(SiglumeClientError, match="target_tier is required"):
            client.create_plan_web3_mandate("")


def test_account_wrappers_parse_sparse_payloads() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/me/preferences":
            return httpx.Response(200, json=envelope({"language": "en"}))
        if request.url.path == "/v1/me/plan":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "plan": "free",
                        "available_models": [],
                        "available_plans": {},
                        "usage_today": {},
                    }
                ),
            )
        if request.url.path == "/v1/me/plan/billing-portal":
            return httpx.Response(200, json=envelope({"portal_url": "https://billing.example.test/portal/demo"}))
        if request.url.path == "/v1/me/plan/cancel":
            return httpx.Response(200, json=envelope({"cancelled": False}))
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        preferences = client.get_account_preferences()
        plan = client.get_account_plan()
        portal = client.open_plan_billing_portal()
        cancellation = client.cancel_account_plan()

    assert preferences.language == "en"
    assert preferences.interest_profile == {}
    assert plan.plan == "free"
    assert plan.available_models == []
    assert portal.portal_url == "https://billing.example.test/portal/demo"
    assert cancellation.cancelled is False


def test_account_remainder_wrappers_use_direct_routes_and_support_record_replay(tmp_path: Path) -> None:
    cassette_path = tmp_path / "account_remainder_roundtrip.json"
    requests: list[tuple[str, str, object]] = []

    def handler(request: httpx.Request) -> httpx.Response:
        body: object = json.loads(request.content.decode("utf-8")) if request.content else {}
        requests.append((request.method, request.url.path, body))

        if request.url.path == "/v1/me/watchlist" and request.method == "GET":
            return httpx.Response(200, json=envelope({"symbols": ["BTC", "ETH"]}))
        if request.url.path == "/v1/me/watchlist" and request.method == "PUT":
            assert body == {"symbols": ["NVDA", "BTC"]}
            return httpx.Response(200, json=envelope({"symbols": ["NVDA", "BTC"]}))
        if request.url.path == "/v1/me/favorites" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "favorites": [
                            {
                                "agent_id": "agt_fav_1",
                                "name": "Macro Lens",
                                "avatar_url": "/macro-lens.png",
                            }
                        ]
                    }
                ),
            )
        if request.url.path == "/v1/me/favorites" and request.method == "POST":
            assert body == {"agent_id": "agt_fav_2"}
            return httpx.Response(200, json=envelope({"ok": True, "status": "added"}))
        if request.url.path == "/v1/me/favorites/agt_fav_2/remove" and request.method == "PUT":
            return httpx.Response(200, json=envelope({"ok": True}))
        if request.url.path == "/v1/post":
            assert body == {"text": "Publish this note.", "lang": "en"}
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "accepted": True,
                        "content_id": "cnt_human_1",
                        "posted_by": "human",
                    }
                ),
            )
        if request.url.path == "/v1/content/cnt_human_1" and request.method == "DELETE":
            return httpx.Response(200, json=envelope({"deleted": True, "content_id": "cnt_human_1"}))
        if request.url.path == "/v1/digests" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "digest_id": "dig_1",
                                "title": "Morning digest",
                                "digest_type": "daily",
                                "summary": "BTC and NVDA moved overnight.",
                                "generated_at": "2026-04-20T07:00:00Z",
                            }
                        ],
                        "next_cursor": None,
                    }
                ),
            )
        if request.url.path == "/v1/digests/dig_1" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "digest_id": "dig_1",
                        "title": "Morning digest",
                        "digest_type": "daily",
                        "summary": "BTC and NVDA moved overnight.",
                        "generated_at": "2026-04-20T07:00:00Z",
                        "items": [
                            {
                                "digest_item_id": "dit_1",
                                "headline": "BTC volatility spike",
                                "summary": "BTC moved 4% in the last hour.",
                                "confidence": 0.91,
                                "trust_state": "verified",
                                "ref_type": "symbol",
                                "ref_id": "BTC",
                            }
                        ],
                    }
                ),
            )
        if request.url.path == "/v1/alerts" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "alert_id": "alt_1",
                                "title": "BTC volatility spike",
                                "summary": "BTC moved more than 4% in the last hour.",
                                "severity": "medium",
                                "confidence": 0.91,
                                "trust_state": "verified",
                                "ref_type": "symbol",
                                "ref_id": "BTC",
                                "created_at": "2026-04-20T08:00:00Z",
                            }
                        ],
                        "next_cursor": None,
                    }
                ),
            )
        if request.url.path == "/v1/alerts/alt_1" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "alert_id": "alt_1",
                        "title": "BTC volatility spike",
                        "summary": "BTC moved more than 4% in the last hour.",
                        "severity": "medium",
                        "confidence": 0.91,
                        "trust_state": "verified",
                        "ref_type": "symbol",
                        "ref_id": "BTC",
                        "created_at": "2026-04-20T08:00:00Z",
                    }
                ),
            )
        if request.url.path == "/v1/feedback" and request.method == "POST":
            assert body == {
                "ref_type": "content",
                "ref_id": "cnt_human_1",
                "feedback_type": "helpful",
                "reason": "clear summary",
            }
            return httpx.Response(200, json=envelope({"accepted": True}))
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.RECORD) as recorder:
        with recorder.wrap(build_client(handler)) as client:
            watchlist = client.get_account_watchlist()
            updated_watchlist = client.update_account_watchlist((" nvda ", "btc"))
            favorites = client.list_account_favorites()
            added = client.add_account_favorite("agt_fav_2")
            removed = client.remove_account_favorite("agt_fav_2")
            posted = client.post_account_content_direct("Publish this note.", lang="en")
            deleted = client.delete_account_content("cnt_human_1")
            digests = client.list_account_digests()
            digest = client.get_account_digest("dig_1")
            alerts = client.list_account_alerts()
            alert = client.get_account_alert("alt_1")
            feedback = client.submit_account_feedback(
                "content",
                "cnt_human_1",
                "helpful",
                reason="clear summary",
            )

    assert watchlist.symbols == ["BTC", "ETH"]
    assert updated_watchlist.symbols == ["NVDA", "BTC"]
    assert favorites[0].agent_id == "agt_fav_1"
    assert added.status == "added"
    assert removed.status == "removed"
    assert posted.accepted is True
    assert posted.content_id == "cnt_human_1"
    assert deleted.deleted is True
    assert digests.items[0].digest_id == "dig_1"
    assert digest.items[0].headline == "BTC volatility spike"
    assert alerts.items[0].alert_id == "alt_1"
    assert alert.severity == "medium"
    assert feedback.accepted is True

    def unexpected_handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError(f"Replay should not hit transport: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.REPLAY) as recorder:
        with recorder.wrap(build_client(unexpected_handler)) as client:
            replay_watchlist = client.get_account_watchlist()
            replay_updated = client.update_account_watchlist((" nvda ", "btc"))
            replay_favorites = client.list_account_favorites()
            replay_added = client.add_account_favorite("agt_fav_2")
            replay_removed = client.remove_account_favorite("agt_fav_2")
            replay_posted = client.post_account_content_direct("Publish this note.", lang="en")
            replay_deleted = client.delete_account_content("cnt_human_1")
            replay_digests = client.list_account_digests()
            replay_digest = client.get_account_digest("dig_1")
            replay_alerts = client.list_account_alerts()
            replay_alert = client.get_account_alert("alt_1")
            replay_feedback = client.submit_account_feedback(
                "content",
                "cnt_human_1",
                "helpful",
                reason="clear summary",
            )

    assert replay_watchlist.symbols == ["BTC", "ETH"]
    assert replay_updated.symbols == ["NVDA", "BTC"]
    assert replay_favorites[0].name == "Macro Lens"
    assert replay_added.agent_id == "agt_fav_2"
    assert replay_removed.agent_id == "agt_fav_2"
    assert replay_posted.posted_by == "human"
    assert replay_deleted.content_id == "cnt_human_1"
    assert replay_digests.items[0].title == "Morning digest"
    assert replay_digest.items[0].ref_id == "BTC"
    assert replay_alerts.items[0].title == "BTC volatility spike"
    assert replay_alert.ref_type == "symbol"
    assert replay_feedback.accepted is True
    assert [path for _, path, _ in requests] == [
        "/v1/me/watchlist",
        "/v1/me/watchlist",
        "/v1/me/favorites",
        "/v1/me/favorites",
        "/v1/me/favorites/agt_fav_2/remove",
        "/v1/post",
        "/v1/content/cnt_human_1",
        "/v1/digests",
        "/v1/digests/dig_1",
        "/v1/alerts",
        "/v1/alerts/alt_1",
        "/v1/feedback",
    ]


def test_account_remainder_wrappers_validate_required_inputs() -> None:
    with build_client(lambda request: httpx.Response(500)) as client:
        with pytest.raises(SiglumeClientError, match="symbols must be a list of strings"):
            client.update_account_watchlist("BTC")  # type: ignore[arg-type]
        with pytest.raises(SiglumeClientError, match="agent_id is required"):
            client.add_account_favorite("")
        with pytest.raises(SiglumeClientError, match="text is required"):
            client.post_account_content_direct("")
        with pytest.raises(SiglumeClientError, match="digest_id is required"):
            client.get_account_digest("")
        with pytest.raises(SiglumeClientError, match="alert_id is required"):
            client.get_account_alert("")
        with pytest.raises(SiglumeClientError, match="ref_type is required"):
            client.submit_account_feedback("", "cnt_1", "helpful")


def test_account_remainder_wrappers_parse_sparse_payloads_and_optional_defaults() -> None:
    requests: list[tuple[str, str, dict[str, object]]] = []

    def handler(request: httpx.Request) -> httpx.Response:
        body = (
            json.loads(request.content.decode("utf-8"))
            if request.content
            else {}
        )
        requests.append((request.method, request.url.path, body))
        if request.url.path == "/v1/me/watchlist":
            return httpx.Response(200, json=envelope({"symbols": ["AAPL", 123, None]}))
        if request.url.path == "/v1/me/favorites" and request.method == "GET":
            return httpx.Response(200, json=envelope({"favorites": None}))
        if request.url.path == "/v1/me/favorites" and request.method == "POST":
            return httpx.Response(200, json=envelope({"ok": False}))
        if request.url.path == "/v1/me/favorites/agt_sparse/remove":
            return httpx.Response(200, json=envelope({"ok": True, "agent_id": "agt_sparse"}))
        if request.url.path == "/v1/post":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "accepted": False,
                        "error": "rate_limited",
                        "limit_reached": True,
                    }
                ),
            )
        if request.url.path == "/v1/content/cnt_sparse":
            return httpx.Response(200, json=envelope({"deleted": False}))
        if request.url.path == "/v1/digests":
            return httpx.Response(200, json=envelope({"items": "skip-me", "next_cursor": 123}))
        if request.url.path == "/v1/digests/dig_sparse":
            return httpx.Response(200, json=envelope({"digest_id": "dig_sparse", "items": "skip-me"}))
        if request.url.path == "/v1/alerts":
            return httpx.Response(200, json=envelope({"items": [None, "bad"]}))
        if request.url.path == "/v1/alerts/alt_sparse":
            return httpx.Response(200, json=envelope({"alert_id": "alt_sparse", "confidence": None}))
        if request.url.path == "/v1/feedback":
            return httpx.Response(200, json=envelope({"accepted": False}))
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        watchlist = client.get_account_watchlist()
        favorites = client.list_account_favorites()
        added = client.add_account_favorite("agt_sparse")
        removed = client.remove_account_favorite("agt_sparse")
        posted = client.post_account_content_direct("  Sparse post  ")
        deleted = client.delete_account_content("cnt_sparse")
        digests = client.list_account_digests()
        digest = client.get_account_digest("dig_sparse")
        alerts = client.list_account_alerts()
        alert = client.get_account_alert("alt_sparse")
        feedback = client.submit_account_feedback("content", "cnt_sparse", "not-helpful")

    assert watchlist.symbols == ["AAPL"]
    assert favorites == []
    assert added.ok is False
    assert added.status is None
    assert added.agent_id == "agt_sparse"
    assert removed.ok is True
    assert removed.status == "removed"
    assert removed.agent_id == "agt_sparse"
    assert posted.accepted is False
    assert posted.error == "rate_limited"
    assert posted.limit_reached is True
    assert deleted.deleted is False
    assert deleted.content_id is None
    assert digests.items == []
    assert digests.next_cursor == "123"
    assert digest.digest_id == "dig_sparse"
    assert digest.items == []
    assert alerts.items == []
    assert alerts.next_cursor is None
    assert alert.alert_id == "alt_sparse"
    assert alert.confidence == 0
    assert alert.trust_state is None
    assert feedback.accepted is False
    assert ("POST", "/v1/post", {"text": "Sparse post"}) in requests
    assert (
        "POST",
        "/v1/feedback",
        {
            "ref_type": "content",
            "ref_id": "cnt_sparse",
            "feedback_type": "not-helpful",
        },
    ) in requests


def test_network_and_agent_read_wrappers_round_trip_through_recorder(tmp_path: Path) -> None:
    requests: list[tuple[str, str, dict[str, str]]] = []
    cassette_path = tmp_path / "network_and_agent_reads.json"

    def handler(request: httpx.Request) -> httpx.Response:
        params = dict(request.url.params)
        requests.append((request.method, request.url.path, params))
        if request.url.path == "/v1/home":
            assert params == {"limit": "2", "feed": "hot", "query": "macro"}
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "item_id": "cnt_home_1",
                                "item_type": "post",
                                "title": "AI infra demand spikes",
                                "summary": "Accelerator demand remains elevated.",
                                "ref_type": "content",
                                "ref_id": "cnt_home_1",
                                "created_at": "2026-04-20T09:00:00Z",
                                "agent_id": "agt_market_1",
                                "agent_name": "Market Lens",
                                "trust_state": "verified",
                                "confidence": 0.92,
                                "reply_count": 3,
                                "thread_reply_count": 4,
                                "source_uri": "https://infra.example/report",
                                "posted_by": "ai",
                            },
                            {
                                "item_id": "cnt_home_2",
                                "item_type": "post",
                                "title": "Chip supply normalizes",
                                "summary": "Lead times eased during the last week.",
                                "ref_type": "content",
                                "ref_id": "cnt_home_2",
                                "created_at": "2026-04-20T08:55:00Z",
                                "agent_id": "agt_market_2",
                                "agent_name": "Supply Scout",
                                "trust_state": "mixed",
                                "confidence": 0.81,
                                "reply_count": 1,
                                "thread_reply_count": 1,
                                "source_uri": "https://supply.example/update",
                                "posted_by": "ai",
                            },
                        ],
                        "next_cursor": None,
                        "limit": 2,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/content/cnt_home_1":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "content_id": "cnt_home_1",
                        "agent_id": "agt_market_1",
                        "thread_id": "thr_home_1",
                        "message_type": "analysis",
                        "visibility": "network_public",
                        "title": "AI infra demand spikes",
                        "body": {"summary": "Accelerator demand remains elevated."},
                        "claims": ["clm_home_1"],
                        "evidence_refs": ["evd_home_1"],
                        "trust_state": "verified",
                        "confidence": 0.92,
                        "created_at": "2026-04-20T09:00:00Z",
                        "presentation": {"title": "AI infra demand spikes"},
                        "signal_packet": {"subject": "AI infra demand spikes"},
                        "posted_by": "ai",
                    }
                ),
            )
        if request.url.path == "/v1/content":
            assert params == {"ids": "cnt_home_1,cnt_home_2"}
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "item_id": "cnt_home_1",
                                "item_type": "post",
                                "title": "AI infra demand spikes",
                                "summary": "Accelerator demand remains elevated.",
                                "ref_type": "content",
                                "ref_id": "cnt_home_1",
                                "created_at": "2026-04-20T09:00:00Z",
                                "agent_id": "agt_market_1",
                                "agent_name": "Market Lens",
                                "reply_count": 3,
                                "posted_by": "ai",
                            },
                            {
                                "item_id": "cnt_home_2",
                                "item_type": "post",
                                "title": "Chip supply normalizes",
                                "summary": "Lead times eased during the last week.",
                                "ref_type": "content",
                                "ref_id": "cnt_home_2",
                                "created_at": "2026-04-20T08:55:00Z",
                                "agent_id": "agt_market_2",
                                "agent_name": "Supply Scout",
                                "reply_count": 1,
                                "posted_by": "ai",
                            },
                        ]
                    }
                ),
            )
        if request.url.path == "/v1/content/cnt_home_1/replies":
            assert params == {"limit": "10"}
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "replies": [
                            {
                                "content_id": "cnt_reply_1",
                                "title": "Demand still looks elevated",
                                "summary": "Follow-up post agreeing with the thesis.",
                                "created_at": "2026-04-20T09:05:00Z",
                                "agent_id": "agt_reply_1",
                                "agent_name": "Macro Reply",
                                "reply_to_agent_name": "Market Lens",
                                "stance": "support",
                                "reply_count": 0,
                                "posted_by": "ai",
                            }
                        ],
                        "context_head": {
                            "content_id": "cnt_home_1",
                            "title": "AI infra demand spikes",
                            "summary": "Accelerator demand remains elevated.",
                            "agent_id": "agt_market_1",
                            "agent_name": "Market Lens",
                        },
                        "thread_summary": "One supporting reply so far.",
                        "thread_surface_scores": [{"domain": "infra.example", "score": 82}],
                        "total_count": 1,
                        "next_cursor": None,
                    }
                ),
            )
        if request.url.path == "/v1/claims/clm_home_1":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "claim_id": "clm_home_1",
                        "claim_type": "market_signal",
                        "normalized_text": "Accelerator demand remains elevated across hyperscaler buyers.",
                        "confidence": 0.91,
                        "trust_state": "verified",
                        "evidence_refs": ["evd_home_1"],
                        "signal_packet": {"subject": "AI infra demand spikes"},
                    }
                ),
            )
        if request.url.path == "/v1/evidence/evd_home_1":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "evidence_id": "evd_home_1",
                        "evidence_type": "press_release",
                        "uri": "https://infra.example/report",
                        "excerpt": "Management reaffirmed strong accelerator demand.",
                        "source_reliability": 0.88,
                        "signal_packet": {"source_type": "press_release"},
                    }
                ),
            )
        if request.url.path.startswith("/v1/agent/"):
            assert request.headers["X-Agent-Key"] == "agtk_test_key"
        if request.url.path == "/v1/agent/me":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "agent_id": "agt_self_1",
                        "agent_type": "personal",
                        "name": "Signal Scout",
                        "avatar_url": "/avatars/signal-scout.png",
                        "description": "Monitors the public network for market signals.",
                        "status": "active",
                        "capabilities": {"network": True},
                        "settings": {"mode": "observant"},
                    }
                ),
            )
        if request.url.path == "/v1/agent/topics":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "topics": [
                            {"topic_key": "ai.infrastructure", "priority": 10},
                            {"topic_key": "semiconductors", "priority": 8},
                        ]
                    }
                ),
            )
        if request.url.path == "/v1/agent/feed":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "content_id": "cnt_agent_1",
                                "message_type": "analysis",
                                "title": "Model serving costs fell",
                                "trust_state": "verified",
                                "confidence": 0.86,
                                "created_at": "2026-04-20T07:30:00Z",
                            }
                        ]
                    }
                ),
            )
        if request.url.path == "/v1/agent/content/cnt_agent_1":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "content_id": "cnt_agent_1",
                        "agent_id": "agt_self_1",
                        "thread_id": "thr_agent_1",
                        "message_type": "analysis",
                        "visibility": "agent_feed",
                        "title": "Model serving costs fell",
                        "body": {"summary": "Spot instance prices moved lower overnight."},
                        "claims": ["clm_home_1"],
                        "evidence_refs": ["evd_home_1"],
                        "trust_state": "verified",
                        "confidence": 0.86,
                        "created_at": "2026-04-20T07:30:00Z",
                        "presentation": {"title": "Model serving costs fell"},
                        "signal_packet": {"subject": "Model serving costs"},
                        "posted_by": "ai",
                    }
                ),
            )
        if request.url.path == "/v1/agent/threads/thr_agent_1":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "thread_id": "thr_agent_1",
                        "items": [
                            {
                                "content_id": "cnt_agent_1",
                                "agent_id": "agt_self_1",
                                "thread_id": "thr_agent_1",
                                "message_type": "analysis",
                                "visibility": "agent_feed",
                                "title": "Model serving costs fell",
                                "body": {"summary": "Spot instance prices moved lower overnight."},
                                "claims": ["clm_home_1"],
                                "evidence_refs": ["evd_home_1"],
                                "trust_state": "verified",
                                "confidence": 0.86,
                                "created_at": "2026-04-20T07:30:00Z",
                                "presentation": {"title": "Model serving costs fell"},
                                "signal_packet": {"subject": "Model serving costs"},
                                "posted_by": "ai",
                            }
                        ],
                    }
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.RECORD) as recorder:
        with recorder.wrap(build_client(handler, agent_key="agtk_test_key")) as client:
            home = client.get_network_home(feed="hot", limit=2, query="macro")
            batch = client.get_network_content_batch(["cnt_home_1", "cnt_home_2"])
            detail = client.get_network_content("cnt_home_1")
            replies = client.list_network_content_replies("cnt_home_1", limit=10)
            claim = client.get_network_claim("clm_home_1")
            evidence = client.get_network_evidence("evd_home_1")
            agent_profile = client.get_agent_profile()
            topics = client.list_agent_topics()
            feed = client.get_agent_feed()
            agent_content = client.get_agent_content("cnt_agent_1")
            thread = client.get_agent_thread("thr_agent_1")

    assert home.items[0].content_id == "cnt_home_1"
    assert batch[1].agent_name == "Supply Scout"
    assert detail.claims == ["clm_home_1"]
    assert replies.context_head is not None
    assert replies.context_head.content_id == "cnt_home_1"
    assert replies.replies[0].reply_to_agent_name == "Market Lens"
    assert claim.evidence_refs == ["evd_home_1"]
    assert evidence.uri == "https://infra.example/report"
    assert agent_profile.agent_id == "agt_self_1"
    assert agent_profile.settings == {"mode": "observant"}
    assert topics[0].topic_key == "ai.infrastructure"
    assert feed[0].content_id == "cnt_agent_1"
    assert agent_content.thread_id == "thr_agent_1"
    assert thread.items[0].content_id == "cnt_agent_1"

    def unexpected_handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError(f"Replay should not hit transport: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.REPLAY) as recorder:
        with recorder.wrap(build_client(unexpected_handler, agent_key="agtk_test_key")) as client:
            replay_home = client.get_network_home(feed="hot", limit=2, query="macro")
            replay_batch = client.get_network_content_batch(["cnt_home_1", "cnt_home_2"])
            replay_detail = client.get_network_content("cnt_home_1")
            replay_replies = client.list_network_content_replies("cnt_home_1", limit=10)
            replay_claim = client.get_network_claim("clm_home_1")
            replay_evidence = client.get_network_evidence("evd_home_1")
            replay_agent_profile = client.get_agent_profile()
            replay_topics = client.list_agent_topics()
            replay_feed = client.get_agent_feed()
            replay_agent_content = client.get_agent_content("cnt_agent_1")
            replay_thread = client.get_agent_thread("thr_agent_1")

    assert replay_home.items[0].title == "AI infra demand spikes"
    assert replay_batch[0].content_id == "cnt_home_1"
    assert replay_detail.evidence_refs == ["evd_home_1"]
    assert replay_replies.total_count == 1
    assert replay_claim.claim_id == "clm_home_1"
    assert replay_evidence.evidence_type == "press_release"
    assert replay_agent_profile.name == "Signal Scout"
    assert replay_topics[1].priority == 8
    assert replay_feed[0].title == "Model serving costs fell"
    assert replay_agent_content.agent_id == "agt_self_1"
    assert replay_thread.thread_id == "thr_agent_1"
    assert [path for _, path, _ in requests] == [
        "/v1/home",
        "/v1/content",
        "/v1/content/cnt_home_1",
        "/v1/content/cnt_home_1/replies",
        "/v1/claims/clm_home_1",
        "/v1/evidence/evd_home_1",
        "/v1/agent/me",
        "/v1/agent/topics",
        "/v1/agent/feed",
        "/v1/agent/content/cnt_agent_1",
        "/v1/agent/threads/thr_agent_1",
    ]


def test_network_and_agent_read_wrappers_validate_required_inputs() -> None:
    with build_client(lambda request: httpx.Response(500), agent_key="agtk_test_key") as client:
        with pytest.raises(SiglumeClientError, match="content_ids must be a list of strings"):
            client.get_network_content_batch("cnt_1")  # type: ignore[arg-type]
        with pytest.raises(SiglumeClientError, match="content_ids must contain only strings"):
            client.get_network_content_batch(["cnt_1", 123])  # type: ignore[list-item]
        with pytest.raises(SiglumeClientError, match="content_ids must contain at least one content id"):
            client.get_network_content_batch([])
        with pytest.raises(SiglumeClientError, match="content_ids must contain at most 20 ids"):
            client.get_network_content_batch([f"cnt_{index}" for index in range(21)])
        with pytest.raises(SiglumeClientError, match="content_id is required"):
            client.get_network_content("")
        with pytest.raises(SiglumeClientError, match="content_id is required"):
            client.list_network_content_replies("")
        with pytest.raises(SiglumeClientError, match="claim_id is required"):
            client.get_network_claim("")
        with pytest.raises(SiglumeClientError, match="evidence_id is required"):
            client.get_network_evidence("")
        with pytest.raises(SiglumeClientError, match="content_id is required"):
            client.get_agent_content("")
        with pytest.raises(SiglumeClientError, match="thread_id is required"):
            client.get_agent_thread("")

    with build_client(lambda request: httpx.Response(500)) as client_without_agent_key:
        with pytest.raises(SiglumeClientError, match="agent_key is required for agent\\.\\* routes"):
            client_without_agent_key.get_agent_profile()
        with pytest.raises(SiglumeClientError, match="agent_key is required for agent\\.\\* routes"):
            client_without_agent_key.list_agent_topics()


def test_network_and_agent_read_wrappers_parse_sparse_payloads() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/home":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {"item_id": "cnt_sparse", "confidence": None},
                            "skip-me",
                        ],
                        "next_cursor": "cursor_sparse",
                        "limit": 2,
                        "offset": 1,
                    }
                ),
            )
        if request.url.path == "/v1/content/cnt_sparse":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "content_id": "cnt_sparse",
                        "claims": [1, "clm_sparse", None],
                        "evidence_refs": "not-a-list",
                        "body": "skip-me",
                        "presentation": None,
                    }
                ),
            )
        if request.url.path == "/v1/content":
            return httpx.Response(200, json=envelope({"items": [None, {"ref_id": "cnt_sparse"}]}))
        if request.url.path == "/v1/content/cnt_sparse/replies":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "replies": ["skip", {"content_id": "cnt_reply_sparse"}],
                        "context_head": "skip",
                        "thread_surface_scores": "skip",
                        "total_count": None,
                        "next_cursor": None,
                    }
                ),
            )
        if request.url.path == "/v1/claims/clm_sparse":
            return httpx.Response(
                200,
                json=envelope({"claim_id": "clm_sparse", "evidence_refs": [None, "evd_sparse"], "signal_packet": "skip"})
            )
        if request.url.path == "/v1/evidence/evd_sparse":
            return httpx.Response(200, json=envelope({"evidence_id": "evd_sparse", "source_reliability": None}))
        if request.url.path.startswith("/v1/agent/"):
            assert request.headers["X-Agent-Key"] == "agtk_test_key"
        if request.url.path == "/v1/agent/me":
            return httpx.Response(200, json=envelope({"agent_id": "agt_sparse"}))
        if request.url.path == "/v1/agent/topics":
            return httpx.Response(200, json=envelope({"topics": ["skip", {"topic_key": "ai.infra", "priority": None}]}))
        if request.url.path == "/v1/agent/feed":
            return httpx.Response(200, json=envelope({"items": [None, {"content_id": "cnt_feed_sparse"}]}))
        if request.url.path == "/v1/agent/content/cnt_agent_sparse":
            return httpx.Response(200, json=envelope({"content_id": "cnt_agent_sparse", "claims": "skip"}))
        if request.url.path == "/v1/agent/threads/thr_sparse":
            return httpx.Response(200, json=envelope({"thread_id": "thr_sparse", "items": ["skip", {"content_id": "cnt_agent_sparse"}]}))
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler, agent_key="agtk_test_key") as client:
        home = client.get_network_home(limit=2)
        detail = client.get_network_content("cnt_sparse")
        batch = client.get_network_content_batch(["cnt_sparse"])
        replies = client.list_network_content_replies("cnt_sparse")
        claim = client.get_network_claim("clm_sparse")
        evidence = client.get_network_evidence("evd_sparse")
        profile = client.get_agent_profile()
        topics = client.list_agent_topics()
        feed = client.get_agent_feed()
        agent_content = client.get_agent_content("cnt_agent_sparse")
        thread = client.get_agent_thread("thr_sparse")

    assert home.items[0].content_id == "cnt_sparse"
    assert home.items[0].confidence == 0.0
    assert home.next_cursor == "cursor_sparse"
    assert detail.claims == ["clm_sparse"]
    assert detail.evidence_refs == []
    assert detail.body == {}
    assert batch[0].content_id == "cnt_sparse"
    assert replies.replies[0].content_id == "cnt_reply_sparse"
    assert replies.context_head is None
    assert replies.thread_surface_scores == []
    assert replies.total_count == 0
    assert claim.evidence_refs == ["evd_sparse"]
    assert claim.signal_packet == {}
    assert evidence.source_reliability == 0.0
    assert profile.agent_id == "agt_sparse"
    assert topics[0].priority == 0
    assert feed[0].content_id == "cnt_feed_sparse"
    assert agent_content.claims == []
    assert thread.items[0].content_id == "cnt_agent_sparse"


def test_portal_grants_accounts_support_and_submit_review_are_typed() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/market/developer/portal":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "platform": {"developer_portal_url": "https://siglume.com/owner/publish"},
                        "monetization": {"developer_share_bps": 9340},
                        "payout_readiness": {"verified_destination": True},
                        "listings": {"total_count": 2},
                        "usage": {"event_count": 12},
                        "support": {"open_case_count": 1},
                        "apps": [
                            {
                                "id": "lst_1",
                                "capability_key": "price-compare-helper",
                                "name": "Price Compare Helper",
                                "status": "published",
                                "dry_run_supported": True,
                                "price_model": "free",
                                "price_value_minor": 0,
                                "currency": "USD",
                            }
                        ],
                    }
                ),
            )
        if request.url.path == "/v1/market/sandbox/sessions":
            body = json.loads(request.content.decode("utf-8"))
            assert body["capability_key"] == "price-compare-helper"
            return httpx.Response(
                201,
                json=envelope(
                    {
                        "session_id": "ses_123",
                        "agent_id": "agt_123",
                        "capability_key": "price-compare-helper",
                        "environment": "sandbox",
                        "dry_run_supported": True,
                        "approval_mode": "auto",
                    }
                ),
            )
        if request.url.path == "/v1/market/access-grants":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "grt_123",
                                "capability_listing_id": "lst_1",
                                "grant_status": "active",
                                "billing_model": "subscription",
                                "bindings": [],
                            }
                        ],
                        "next_cursor": None,
                        "limit": 20,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/market/access-grants/grt_123/bind-agent":
            body = json.loads(request.content.decode("utf-8"))
            assert body["agent_id"] == "agt_123"
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "binding": {
                            "id": "bnd_123",
                            "access_grant_id": "grt_123",
                            "agent_id": "agt_123",
                            "binding_status": "active",
                        },
                        "access_grant": {
                            "id": "grt_123",
                            "capability_listing_id": "lst_1",
                            "grant_status": "active",
                            "billing_model": "subscription",
                            "bindings": [],
                        },
                    }
                ),
            )
        if request.url.path == "/v1/market/connected-accounts":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "ca_123",
                                "provider_key": "slack",
                                "account_role": "publisher",
                                "display_name": "Team Slack",
                                "environment": "live",
                                "connection_status": "connected",
                                "scopes": ["chat:write"],
                            }
                        ],
                        "next_cursor": None,
                        "limit": 50,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/market/support-cases" and request.method == "POST":
            body = json.loads(request.content.decode("utf-8"))
            assert body["summary"] == "Missing receipt\n\nPlease investigate the missing receipt."
            assert body["trace_id"] == "trc_support"
            return httpx.Response(
                201,
                json=envelope(
                    {
                        "id": "sup_123",
                        "case_type": "app_execution",
                        "summary": body["summary"],
                        "status": "open",
                        "trace_id": "trc_support",
                    }
                ),
            )
        if request.url.path == "/v1/market/support-cases" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "sup_123",
                                "case_type": "app_execution",
                                "summary": "Missing receipt\n\nPlease investigate the missing receipt.",
                                "status": "open",
                                "trace_id": "trc_support",
                            }
                        ],
                        "next_cursor": None,
                        "limit": 50,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/market/capabilities/lst_1/submit-review":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "id": "lst_1",
                        "capability_key": "price-compare-helper",
                        "name": "Price Compare Helper",
                        "status": "pending_review",
                        "dry_run_supported": True,
                        "price_model": "free",
                        "price_value_minor": 0,
                        "currency": "USD",
                    }
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        portal = client.get_developer_portal()
        sandbox = client.create_sandbox_session(agent_id="agt_123", capability_key="price-compare-helper")
        grants = client.list_access_grants()
        binding = client.bind_agent_to_grant("grt_123", agent_id="agt_123")
        accounts = client.list_connected_accounts()
        support_case = client.create_support_case("Missing receipt", "Please investigate the missing receipt.", trace_id="trc_support")
        support_cases = client.list_support_cases()
        review = client.submit_review("lst_1")

    assert portal.apps[0].capability_key == "price-compare-helper"
    assert sandbox.session_id == "ses_123"
    assert grants.items[0].grant_status == "active"
    assert binding.binding.binding_status == "active"
    assert accounts.items[0].provider_key == "slack"
    assert support_case.trace_id == "trc_support"
    assert support_cases.items[0].support_case_id == "sup_123"
    assert review.status == "pending_review"


def test_preview_quality_score_maps_server_validation_and_quality_issues() -> None:
    tool_manual = build_tool_manual()

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/market/tool-manuals/preview-quality"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload["tool_manual"]["tool_name"] == tool_manual.tool_name
        return httpx.Response(
            200,
            json=envelope(
                {
                    "ok": False,
                    "errors": [
                        {
                            "code": "MISSING_FIELD",
                            "message": "usage_hints is missing",
                            "field": "usage_hints",
                        }
                    ],
                    "warnings": [],
                    "quality": {
                        "overall_score": 78,
                        "grade": "B",
                        "keyword_coverage_estimate": 61,
                        "issues": [
                            {
                                "category": "trigger_specificity",
                                "severity": "warning",
                                "message": "Trigger conditions could be more concrete.",
                                "suggestion": "Use explicit nouns and verbs.",
                            }
                        ],
                        "improvement_suggestions": ["Add one more concrete trigger example."],
                    },
                }
            ),
        )

    with build_client(handler) as client:
        report = client.preview_quality_score(tool_manual)

    assert report.overall_score == 78
    assert report.grade == "B"
    assert report.publishable is False
    assert report.validation_ok is False
    assert report.keyword_coverage_estimate == 61
    assert [issue.code for issue in report.validation_errors] == ["MISSING_FIELD"]
    assert report.validation_warnings == []
    assert [issue.code for issue in report.issues] == ["MISSING_FIELD", "trigger_specificity"]
    assert report.improvement_suggestions == ["Add one more concrete trigger example."]


def test_auto_register_uses_source_url_without_sending_source_code() -> None:
    manifest = build_manifest()
    tool_manual = build_tool_manual()

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/market/capabilities/auto-register"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload["source_url"] == "https://github.com/example/repo/blob/main/app.py"
        assert "source_code" not in payload
        return httpx.Response(
            201,
            json=envelope(
                {
                    "listing_id": "lst_url",
                    "status": "draft",
                    "auto_manifest": {"capability_key": manifest.capability_key},
                    "confidence": {},
                    "review_url": None,
                }
            ),
        )

    with build_client(handler) as client:
        receipt = client.auto_register(
            manifest,
            tool_manual,
            source_url="https://github.com/example/repo/blob/main/app.py",
        )

    assert receipt.listing_id == "lst_url"


def test_preview_quality_score_preserves_zero_values_from_canonical_fields() -> None:
    tool_manual = build_tool_manual()

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/market/tool-manuals/preview-quality"
        return httpx.Response(
            200,
            json=envelope(
                {
                    "ok": True,
                    "errors": [],
                    "warnings": [],
                    "quality": {
                        "overall_score": 0,
                        "score": 91,
                        "grade": "F",
                        "publishable": False,
                        "keyword_coverage_estimate": 0,
                        "keyword_coverage": 44,
                        "issues": [],
                        "improvement_suggestions": [],
                    },
                }
            ),
        )

    with build_client(handler) as client:
        report = client.preview_quality_score(tool_manual)

    assert report.overall_score == 0
    assert report.keyword_coverage_estimate == 0


def test_retry_and_api_error_capture_status_code_and_trace_id() -> None:
    attempts = {"count": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        attempts["count"] += 1
        if attempts["count"] == 1:
            return httpx.Response(503, headers={"Retry-After": "0"})
        return httpx.Response(
            409,
            json={
                "error": {
                    "code": "CONFLICT",
                    "message": "Listing already exists.",
                    "details": {"capability_key": "price-compare-helper"},
                },
                "meta": {"trace_id": "trc_conflict", "request_id": "req_conflict"},
            },
        )

    with build_client(handler) as client:
        try:
            client.get_listing("lst_conflict")
        except SiglumeAPIError as exc:
            error = exc
        else:
            raise AssertionError("Expected SiglumeAPIError to be raised.")

    assert attempts["count"] == 2
    assert error.status_code == 409
    assert error.error_code == "CONFLICT"
    assert error.trace_id == "trc_conflict"
    assert error.details["capability_key"] == "price-compare-helper"


def test_list_agents_without_query_returns_personal_agent_singleton() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/me/agent"
        return httpx.Response(
            200,
            json=envelope(
                {
                    "agent_id": "agt_owner_demo",
                    "agent_type": "personal",
                    "name": "Owner Demo",
                    "avatar_url": "/avatars/owner-demo.png",
                    "description": "Owner-managed marketplace agent.",
                    "status": "active",
                    "capabilities": {"marketplace": True},
                    "settings": {"paused": False},
                }
            ),
        )

    with build_client(handler) as client:
        agents = client.list_agents()

    assert len(agents) == 1
    assert agents[0].agent_id == "agt_owner_demo"
    assert agents[0].capabilities["marketplace"] is True
    assert agents[0].settings["paused"] is False


def test_list_agents_with_query_and_get_agent_parse_search_and_profile_shapes() -> None:
    search_calls: list[dict[str, str | None]] = []

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/search/agents":
            assert request.url.params["query"] == "budget"
            search_calls.append(
                {
                    "cursor": request.url.params.get("cursor"),
                    "limit": request.url.params.get("limit"),
                }
            )
            if request.url.params.get("cursor") == "next_agents":
                return httpx.Response(
                    200,
                    json=envelope(
                        {
                            "items": [
                                {
                                    "agent_id": "agt_budget_helper",
                                    "name": "Budget Helper",
                                    "avatar_url": "/avatars/budget-helper.png",
                                    "description": "Tracks cautious purchasing rules.",
                                    "expertise": ["budgeting"],
                                    "post_count": 1,
                                    "reply_count": 0,
                                }
                            ],
                            "next_cursor": None,
                        }
                    ),
                )
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "agent_id": "agt_budget_demo",
                                "name": "Budget Demo",
                                "avatar_url": "/avatars/budget-demo.png",
                                "description": "Focuses on budget-safe travel purchases.",
                                "expertise": ["travel", "budgeting"],
                                "post_count": 3,
                                "reply_count": 1,
                            }
                        ],
                        "next_cursor": "next_agents",
                    }
                ),
            )
        if request.url.path == "/v1/agents/agt_budget_demo/profile":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "agent_id": "agt_budget_demo",
                        "name": "Budget Demo",
                        "avatar_url": "/avatars/budget-demo.png",
                        "description": "Focuses on budget-safe travel purchases.",
                        "agent_type": "personal",
                        "expertise": ["travel", "budgeting"],
                        "style": "careful",
                        "paused": False,
                        "manifesto_text": "Prefer clear budgets and explicit approvals.",
                        "plan": {"tier": "pro"},
                        "reputation": {"score": 0.92},
                        "post_count": 3,
                        "reply_count": 1,
                        "items": [{"content_id": "cnt_demo_1", "title": "Travel safety checklist"}],
                        "next_cursor": None,
                    }
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        agents = client.list_agents(query="budget", limit=5)
        agent = client.get_agent("agt_budget_demo")

    assert [item.agent_id for item in agents] == ["agt_budget_demo", "agt_budget_helper"]
    assert agents[0].expertise == ["travel", "budgeting"]
    assert agent.manifesto_text == "Prefer clear budgets and explicit approvals."
    assert agent.plan["tier"] == "pro"
    assert agent.items[0]["content_id"] == "cnt_demo_1"
    assert search_calls == [
        {"cursor": None, "limit": "5"},
        {"cursor": "next_agents", "limit": "4"},
    ]


def test_update_agent_charter_maps_charter_text_into_goals_payload() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/charter"
        assert request.method == "PUT"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload["goals"]["charter_text"] == "Prefer capped spend and explicit approval for unusual purchases."
        assert payload["role"] == "buyer"
        assert payload["success_metrics"]["approval_rate_floor"] == 0.8
        assert "wait_for_completion" not in payload
        return httpx.Response(
            200,
            json=envelope(
                {
                    "charter_id": "chr_demo_2",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "version": 2,
                    "active": True,
                    "role": "buyer",
                    "goals": {"charter_text": payload["goals"]["charter_text"]},
                    "target_profile": {},
                    "qualification_criteria": {},
                    "success_metrics": payload["success_metrics"],
                    "constraints": {},
                }
            ),
        )

    with build_client(handler) as client:
        charter = client.update_agent_charter(
            "agt_owner_demo",
            "Prefer capped spend and explicit approval for unusual purchases.",
            role="buyer",
            success_metrics={"approval_rate_floor": 0.8},
            wait_for_completion=True,
        )

    assert charter.charter_id == "chr_demo_2"
    assert charter.charter_text == "Prefer capped spend and explicit approval for unusual purchases."
    assert charter.success_metrics["approval_rate_floor"] == 0.8


def test_update_approval_policy_sanitizes_server_managed_fields() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/approval-policy"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload == {
            "auto_approve_below": {"JPY": 3000},
            "always_require_approval_for": ["travel.booking"],
            "approval_ttl_minutes": 720,
            "structured_only": True,
        }
        return httpx.Response(
            200,
            json=envelope(
                {
                    "approval_policy_id": "apl_demo_2",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "version": 2,
                    "active": True,
                    "auto_approve_below": {"JPY": 3000},
                    "always_require_approval_for": ["travel.booking"],
                    "deny_if": {},
                    "approval_ttl_minutes": 720,
                    "structured_only": True,
                    "merchant_allowlist": [],
                    "merchant_denylist": [],
                    "category_allowlist": [],
                    "category_denylist": [],
                    "risk_policy": {},
                }
            ),
        )

    with build_client(handler) as client:
        policy = client.update_approval_policy(
            "agt_owner_demo",
            {
                "approval_policy_id": "apl_ignore_me",
                "version": 999,
                "auto_approve_below": {"JPY": 3000},
                "always_require_approval_for": ["travel.booking"],
                "approval_ttl_minutes": 720,
                "structured_only": True,
            },
            wait_for_completion=True,
        )

    assert policy.approval_policy_id == "apl_demo_2"
    assert policy.auto_approve_below["JPY"] == 3000
    assert policy.default_requires_approval is True
    assert policy.approval_ttl_minutes == 720


def test_update_budget_policy_sanitizes_server_managed_fields() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/budget"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload == {
            "currency": "JPY",
            "period_limit_minor": 50000,
            "per_order_limit_minor": 12000,
            "auto_approve_below_minor": 3000,
            "metadata": {"source": "sdk-test"},
        }
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_demo_2",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "currency": "JPY",
                    "period_start": "2026-04-01T00:00:00Z",
                    "period_end": "2026-05-01T00:00:00Z",
                    "period_limit_minor": 50000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "per_order_limit_minor": 12000,
                    "auto_approve_below_minor": 3000,
                    "limits": {
                        "period_limit": 50000,
                        "per_order_limit": 12000,
                        "auto_approve_below": 3000,
                    },
                    "metadata": {"source": "sdk-test"},
                }
            ),
        )

    with build_client(handler) as client:
        budget = client.update_budget_policy(
            "agt_owner_demo",
            {
                "budget_id": "bdg_ignore_me",
                "currency": "JPY",
                "period_limit_minor": 50000,
                "per_order_limit_minor": 12000,
                "auto_approve_below_minor": 3000,
                "metadata": {"source": "sdk-test"},
            },
            wait_for_completion=True,
        )

    assert budget.budget_id == "bdg_demo_2"
    assert budget.period_limit_minor == 50000
    assert budget.limits["per_order_limit"] == 12000


def test_update_budget_policy_forwards_null_period_dates_to_clear_them() -> None:
    """period_start / period_end are nullable — sending None must clear the boundary on the server."""

    captured_payload: dict[str, Any] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/budget"
        captured_payload.update(json.loads(request.content.decode("utf-8")))
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_clear_dates",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "currency": "JPY",
                    "period_start": None,
                    "period_end": None,
                    "period_limit_minor": 50000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "limits": {},
                    "metadata": {},
                }
            ),
        )

    with build_client(handler) as client:
        client.update_budget_policy(
            "agt_owner_demo",
            {"period_start": None, "period_end": None},
        )

    assert captured_payload == {"period_start": None, "period_end": None}


def test_update_budget_policy_still_strips_nulls_for_non_nullable_fields() -> None:
    """Non-nullable fields like currency must still be filtered when None is passed."""

    captured_payload: dict[str, Any] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured_payload.update(json.loads(request.content.decode("utf-8")))
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_strip_nonnullable",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "currency": "USD",
                    "period_limit_minor": 1000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "limits": {},
                    "metadata": {},
                }
            ),
        )

    with build_client(handler) as client:
        client.update_budget_policy(
            "agt_owner_demo",
            {"currency": None, "period_limit_minor": 1000},
        )

    assert captured_payload == {"period_limit_minor": 1000}


def test_update_budget_policy_rejects_payload_with_only_filtered_fields() -> None:
    """If the only field provided is a non-nullable None, the whole call should still error."""

    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError("handler should not be called")

    with build_client(handler) as client:
        try:
            client.update_budget_policy("agt_owner_demo", {"currency": None})
        except SiglumeClientError:
            return
    raise AssertionError("Expected SiglumeClientError when the only field is a stripped None")


def test_update_budget_policy_preserves_nullable_period_boundaries() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/budget"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload == {
            "currency": "JPY",
            "period_start": None,
            "period_end": None,
            "period_limit_minor": 9000,
        }
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_nullable",
                    "agent_id": "agt_owner_demo",
                    "currency": "JPY",
                    "period_start": None,
                    "period_end": None,
                    "period_limit_minor": 9000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "per_order_limit_minor": 0,
                    "auto_approve_below_minor": 0,
                    "limits": {},
                    "metadata": {},
                }
            ),
        )

    with build_client(handler) as client:
        budget = client.update_budget_policy(
            "agt_owner_demo",
            {
                "currency": "JPY",
                "period_start": None,
                "period_end": None,
                "period_limit_minor": 9000,
            },
        )

    assert budget.budget_id == "bdg_nullable"
    assert budget.period_start is None
    assert budget.period_end is None


def test_list_operations_uses_owner_operation_catalog_and_execute_route() -> None:
    requests: list[tuple[str, str, dict[str, object]]] = []

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == f"/v1/owner/agents/{DEFAULT_OPERATION_AGENT_ID}/operations":
            assert request.url.params["lang"] == "ja"
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "name": "owner.charter.update",
                                "summary": "Update the owner charter.",
                                "params": "Supports goals and constraints.",
                                "allowed_params": ["goals", "constraints"],
                                "required_params": ["goals"],
                                "requires_params": True,
                                "page_href": "/owner/charters",
                            }
                        ]
                    }
                ),
            )
        if request.url.path == f"/v1/owner/agents/{DEFAULT_OPERATION_AGENT_ID}/operations/execute":
            body = json.loads(request.content.decode("utf-8")) if request.content else {}
            requests.append((request.method, request.url.path, body))
            assert body["operation"] == "owner.charter.update"
            assert body["params"]["goals"]["charter_text"] == "Prefer budget discipline."
            assert body["lang"] == "ja"
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "agent_id": DEFAULT_OPERATION_AGENT_ID,
                        "message": "Updated charter successfully.",
                        "action": "owner_charter_update",
                        "result": {"version": 2},
                    },
                    trace_id="trc_operation",
                    request_id="req_operation",
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        operations = client.list_operations(agent_id=DEFAULT_OPERATION_AGENT_ID, lang="ja")
        operation = client.get_operation_metadata("owner.charter.update", agent_id=DEFAULT_OPERATION_AGENT_ID, lang="ja")
        execution = client.execute_owner_operation(
            DEFAULT_OPERATION_AGENT_ID,
            "owner.charter.update",
            {"goals": {"charter_text": "Prefer budget discipline."}},
            lang="ja",
        )

    assert [item.operation_key for item in operations] == ["owner.charter.update"]
    assert operations[0].permission_class == "action"
    assert operation.required_params == ["goals"]
    assert execution.agent_id == DEFAULT_OPERATION_AGENT_ID
    assert execution.action == "owner_charter_update"
    assert execution.result["version"] == 2
    assert execution.trace_id == "trc_operation"
    assert requests == [
        (
            "POST",
            f"/v1/owner/agents/{DEFAULT_OPERATION_AGENT_ID}/operations/execute",
            {
                "operation": "owner.charter.update",
                "params": {"goals": {"charter_text": "Prefer budget discipline."}},
                "lang": "ja",
            },
        )
    ]


def test_list_operations_falls_back_to_bundled_catalog_when_route_unavailable() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/me/agent":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "agent_id": DEFAULT_OPERATION_AGENT_ID,
                        "agent_type": "personal",
                        "name": "Owner Demo",
                    }
                ),
            )
        if request.url.path == f"/v1/owner/agents/{DEFAULT_OPERATION_AGENT_ID}/operations":
            return httpx.Response(404, json={"error": {"code": "NOT_FOUND", "message": "missing"}})
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        operations = client.list_operations(lang="en")

    assert {item.operation_key for item in operations} >= {
        "owner.charter.get",
        "owner.charter.update",
        "owner.approval_policy.get",
        "owner.budget.update",
    }
    assert all(item.agent_id == DEFAULT_OPERATION_AGENT_ID for item in operations)
