from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import httpx


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from siglume_api_sdk import (  # noqa: E402
    AppCategory,
    AppManifest,
    ApprovalMode,
    PermissionClass,
    PriceModel,
    SiglumeAPIError,
    SiglumeClient,
    SiglumeClientError,
    ToolManual,
    ToolManualPermissionClass,
)
from siglume_api_sdk.testing import Recorder, RecordMode  # noqa: E402


def envelope(data, *, trace_id: str = "trc_test", request_id: str = "req_test") -> dict[str, object]:
    return {
        "data": data,
        "meta": {"request_id": request_id, "trace_id": trace_id},
        "error": None,
    }


def build_manifest() -> AppManifest:
    return AppManifest(
        capability_key="price-compare-helper",
        name="Price Compare Helper",
        job_to_be_done="Compare retailer prices for a product and return the best current offer.",
        category=AppCategory.COMMERCE,
        permission_class=PermissionClass.READ_ONLY,
        approval_mode=ApprovalMode.AUTO,
        dry_run_supported=True,
        required_connected_accounts=[],
        price_model=PriceModel.FREE,
        jurisdiction="US",
        short_description="Search multiple retailers and summarize the best current price.",
        example_prompts=["Compare prices for Sony WH-1000XM5."],
    )


def build_tool_manual() -> ToolManual:
    return ToolManual(
        tool_name="price_compare_helper",
        job_to_be_done="Search multiple retailers for a product and return a ranked price comparison the agent can cite.",
        summary_for_model="Looks up current retailer offers and returns a structured comparison with the best deal first.",
        trigger_conditions=[
            "owner asks to compare prices for a product before deciding where to buy",
            "agent needs retailer offer data to support a shopping recommendation",
            "request is to find the cheapest or best-value option for a product query",
        ],
        do_not_use_when=[
            "the request is to complete checkout or place an order instead of comparing offers",
        ],
        permission_class=ToolManualPermissionClass.READ_ONLY,
        dry_run_supported=True,
        requires_connected_accounts=[],
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Product name, model number, or search phrase."},
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        output_schema={
            "type": "object",
            "properties": {
                "summary": {"type": "string", "description": "One-line overview of the best available deal."},
                "offers": {"type": "array", "items": {"type": "object"}, "description": "Ranked retailer offers."},
            },
            "required": ["summary", "offers"],
            "additionalProperties": False,
        },
        usage_hints=["Use this tool after the owner has named a product and wants evidence-backed price comparison."],
        result_hints=["Lead with the best offer and then summarize notable trade-offs."],
        error_hints=["If no offers are found, ask for a clearer product name or model number."],
    )


def build_client(handler) -> SiglumeClient:
    return SiglumeClient(
        api_key="sig_test_key",
        base_url="https://api.example.test/v1",
        transport=httpx.MockTransport(handler),
    )


def test_auto_register_and_confirm_registration_return_typed_objects(tmp_path: Path) -> None:
    manifest = build_manifest()
    tool_manual = build_tool_manual()
    requests: list[tuple[str, str, dict[str, object]]] = []
    cassette_path = tmp_path / "auto_register_recorded.json"

    def handler(request: httpx.Request) -> httpx.Response:
        body = json.loads(request.content.decode("utf-8")) if request.content else {}
        requests.append((request.method, request.url.path, body))
        assert request.headers["Authorization"] == "Bearer sig_test_key"

        if request.url.path == "/v1/market/capabilities/auto-register":
            assert body["capability_key"] == manifest.capability_key
            assert "Registration bootstrap generated by SiglumeClient." in body["source_code"]
            return httpx.Response(
                201,
                json=envelope(
                    {
                        "listing_id": "lst_123",
                        "status": "draft",
                        "auto_manifest": {"capability_key": manifest.capability_key},
                        "confidence": {"overall": 0.94},
                        "review_url": "/owner/publish?listing=lst_123",
                    }
                ),
            )

        if request.url.path == "/v1/market/capabilities/lst_123/confirm-auto-register":
            assert body["approved"] is True
            assert body["overrides"]["tool_manual"]["tool_name"] == tool_manual.tool_name
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "listing_id": "lst_123",
                        "status": "pending_review",
                        "release": {"release_id": "rel_123", "release_status": "pending_review"},
                        "quality": {
                            "overall_score": 84,
                            "grade": "B",
                            "issues": [],
                            "improvement_suggestions": ["Add one more retailer-specific trigger example."],
                        },
                    },
                    trace_id="trc_confirm",
                ),
            )

        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.RECORD) as recorder:
        with recorder.wrap(build_client(handler)) as client:
            receipt = client.auto_register(manifest, tool_manual)
            confirmation = client.confirm_registration(receipt.listing_id)

    def unexpected_handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError(f"Replay should not hit transport: {request.method} {request.url}")

    with Recorder(cassette_path, mode=RecordMode.REPLAY) as recorder:
        with recorder.wrap(build_client(unexpected_handler)) as client:
            replay_receipt = client.auto_register(manifest, tool_manual)
            replay_confirmation = client.confirm_registration(replay_receipt.listing_id)

    assert receipt.listing_id == "lst_123"
    assert receipt.trace_id == "trc_test"
    assert confirmation.listing_id == "lst_123"
    assert confirmation.status == "pending_review"
    assert confirmation.quality.overall_score == 84
    assert confirmation.quality.grade == "B"
    assert confirmation.trace_id == "trc_confirm"
    assert requests[0][1] == "/v1/market/capabilities/auto-register"
    assert requests[1][1] == "/v1/market/capabilities/lst_123/confirm-auto-register"
    assert replay_receipt.listing_id == receipt.listing_id
    assert replay_confirmation.quality.grade == confirmation.quality.grade


def test_cursor_pages_follow_next_cursor_for_listings_and_usage() -> None:
    call_counter = {"listings": 0, "usage": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/market/capabilities":
            call_counter["listings"] += 1
            if request.url.params.get("cursor") == "next_listing":
                return httpx.Response(
                    200,
                    json=envelope(
                        {
                            "items": [
                                {
                                    "id": "lst_2",
                                    "capability_key": "calendar-sync",
                                    "name": "Calendar Sync",
                                    "status": "published",
                                    "dry_run_supported": True,
                                    "price_model": "free",
                                    "price_value_minor": 0,
                                    "currency": "USD",
                                }
                            ],
                            "next_cursor": None,
                            "limit": 1,
                            "offset": 1,
                        }
                    ),
                )
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "lst_1",
                                "capability_key": "price-compare-helper",
                                "name": "Price Compare Helper",
                                "status": "draft",
                                "dry_run_supported": True,
                                "price_model": "free",
                                "price_value_minor": 0,
                                "currency": "USD",
                            }
                        ],
                        "next_cursor": "next_listing",
                        "limit": 1,
                        "offset": 0,
                    }
                ),
            )

        if request.url.path == "/v1/market/usage":
            call_counter["usage"] += 1
            if request.url.params.get("cursor") == "next_usage":
                return httpx.Response(
                    200,
                    json=envelope(
                        {
                            "items": [
                                {
                                    "id": "use_2",
                                    "capability_key": "price-compare-helper",
                                    "units_consumed": 3,
                                    "outcome": "success",
                                    "execution_kind": "dry_run",
                                    "created_at": "2026-04-19T00:00:00Z",
                                }
                            ],
                            "next_cursor": None,
                            "limit": 1,
                            "offset": 1,
                        }
                    ),
                )
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "use_1",
                                "capability_key": "price-compare-helper",
                                "units_consumed": 1,
                                "outcome": "success",
                                "execution_kind": "dry_run",
                                "created_at": "2026-04-18T00:00:00Z",
                            }
                        ],
                        "next_cursor": "next_usage",
                        "limit": 1,
                        "offset": 0,
                    }
                ),
            )

        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        listings = client.list_my_listings(limit=1)
        usage = client.get_usage(capability_key="price-compare-helper", limit=1)
        listing_items = listings.all_items()
        usage_items = usage.all_items()

    assert [item.capability_key for item in listing_items] == ["price-compare-helper", "calendar-sync"]
    assert [item.units_consumed for item in usage_items] == [1, 3]
    assert call_counter == {"listings": 2, "usage": 2}


def test_portal_grants_accounts_support_and_submit_review_are_typed() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/market/developer/portal":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "platform": {"developer_portal_url": "https://siglume.com/owner/publish"},
                        "monetization": {"developer_share_bps": 9340},
                        "payout_readiness": {"verified_destination": True},
                        "listings": {"total_count": 2},
                        "usage": {"event_count": 12},
                        "support": {"open_case_count": 1},
                        "apps": [
                            {
                                "id": "lst_1",
                                "capability_key": "price-compare-helper",
                                "name": "Price Compare Helper",
                                "status": "published",
                                "dry_run_supported": True,
                                "price_model": "free",
                                "price_value_minor": 0,
                                "currency": "USD",
                            }
                        ],
                    }
                ),
            )
        if request.url.path == "/v1/market/sandbox/sessions":
            body = json.loads(request.content.decode("utf-8"))
            assert body["capability_key"] == "price-compare-helper"
            return httpx.Response(
                201,
                json=envelope(
                    {
                        "session_id": "ses_123",
                        "agent_id": "agt_123",
                        "capability_key": "price-compare-helper",
                        "environment": "sandbox",
                        "dry_run_supported": True,
                        "approval_mode": "auto",
                    }
                ),
            )
        if request.url.path == "/v1/market/access-grants":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "grt_123",
                                "capability_listing_id": "lst_1",
                                "grant_status": "active",
                                "billing_model": "subscription",
                                "bindings": [],
                            }
                        ],
                        "next_cursor": None,
                        "limit": 20,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/market/access-grants/grt_123/bind-agent":
            body = json.loads(request.content.decode("utf-8"))
            assert body["agent_id"] == "agt_123"
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "binding": {
                            "id": "bnd_123",
                            "access_grant_id": "grt_123",
                            "agent_id": "agt_123",
                            "binding_status": "active",
                        },
                        "access_grant": {
                            "id": "grt_123",
                            "capability_listing_id": "lst_1",
                            "grant_status": "active",
                            "billing_model": "subscription",
                            "bindings": [],
                        },
                    }
                ),
            )
        if request.url.path == "/v1/market/connected-accounts":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "ca_123",
                                "provider_key": "slack",
                                "account_role": "publisher",
                                "display_name": "Team Slack",
                                "environment": "live",
                                "connection_status": "connected",
                                "scopes": ["chat:write"],
                            }
                        ],
                        "next_cursor": None,
                        "limit": 50,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/market/support-cases" and request.method == "POST":
            body = json.loads(request.content.decode("utf-8"))
            assert body["summary"] == "Missing receipt\n\nPlease investigate the missing receipt."
            assert body["trace_id"] == "trc_support"
            return httpx.Response(
                201,
                json=envelope(
                    {
                        "id": "sup_123",
                        "case_type": "app_execution",
                        "summary": body["summary"],
                        "status": "open",
                        "trace_id": "trc_support",
                    }
                ),
            )
        if request.url.path == "/v1/market/support-cases" and request.method == "GET":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "id": "sup_123",
                                "case_type": "app_execution",
                                "summary": "Missing receipt\n\nPlease investigate the missing receipt.",
                                "status": "open",
                                "trace_id": "trc_support",
                            }
                        ],
                        "next_cursor": None,
                        "limit": 50,
                        "offset": 0,
                    }
                ),
            )
        if request.url.path == "/v1/market/capabilities/lst_1/submit-review":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "id": "lst_1",
                        "capability_key": "price-compare-helper",
                        "name": "Price Compare Helper",
                        "status": "pending_review",
                        "dry_run_supported": True,
                        "price_model": "free",
                        "price_value_minor": 0,
                        "currency": "USD",
                    }
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        portal = client.get_developer_portal()
        sandbox = client.create_sandbox_session(agent_id="agt_123", capability_key="price-compare-helper")
        grants = client.list_access_grants()
        binding = client.bind_agent_to_grant("grt_123", agent_id="agt_123")
        accounts = client.list_connected_accounts()
        support_case = client.create_support_case("Missing receipt", "Please investigate the missing receipt.", trace_id="trc_support")
        support_cases = client.list_support_cases()
        review = client.submit_review("lst_1")

    assert portal.apps[0].capability_key == "price-compare-helper"
    assert sandbox.session_id == "ses_123"
    assert grants.items[0].grant_status == "active"
    assert binding.binding.binding_status == "active"
    assert accounts.items[0].provider_key == "slack"
    assert support_case.trace_id == "trc_support"
    assert support_cases.items[0].support_case_id == "sup_123"
    assert review.status == "pending_review"


def test_preview_quality_score_maps_server_validation_and_quality_issues() -> None:
    tool_manual = build_tool_manual()

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/market/tool-manuals/preview-quality"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload["tool_manual"]["tool_name"] == tool_manual.tool_name
        return httpx.Response(
            200,
            json=envelope(
                {
                    "ok": False,
                    "errors": [
                        {
                            "code": "MISSING_FIELD",
                            "message": "usage_hints is missing",
                            "field": "usage_hints",
                        }
                    ],
                    "warnings": [],
                    "quality": {
                        "overall_score": 78,
                        "grade": "B",
                        "keyword_coverage_estimate": 61,
                        "issues": [
                            {
                                "category": "trigger_specificity",
                                "severity": "warning",
                                "message": "Trigger conditions could be more concrete.",
                                "suggestion": "Use explicit nouns and verbs.",
                            }
                        ],
                        "improvement_suggestions": ["Add one more concrete trigger example."],
                    },
                }
            ),
        )

    with build_client(handler) as client:
        report = client.preview_quality_score(tool_manual)

    assert report.overall_score == 78
    assert report.grade == "B"
    assert report.publishable is False
    assert report.validation_ok is False
    assert report.keyword_coverage_estimate == 61
    assert [issue.code for issue in report.validation_errors] == ["MISSING_FIELD"]
    assert report.validation_warnings == []
    assert [issue.code for issue in report.issues] == ["MISSING_FIELD", "trigger_specificity"]
    assert report.improvement_suggestions == ["Add one more concrete trigger example."]


def test_auto_register_uses_source_url_without_sending_source_code() -> None:
    manifest = build_manifest()
    tool_manual = build_tool_manual()

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/market/capabilities/auto-register"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload["source_url"] == "https://github.com/example/repo/blob/main/app.py"
        assert "source_code" not in payload
        return httpx.Response(
            201,
            json=envelope(
                {
                    "listing_id": "lst_url",
                    "status": "draft",
                    "auto_manifest": {"capability_key": manifest.capability_key},
                    "confidence": {},
                    "review_url": None,
                }
            ),
        )

    with build_client(handler) as client:
        receipt = client.auto_register(
            manifest,
            tool_manual,
            source_url="https://github.com/example/repo/blob/main/app.py",
        )

    assert receipt.listing_id == "lst_url"


def test_preview_quality_score_preserves_zero_values_from_canonical_fields() -> None:
    tool_manual = build_tool_manual()

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/market/tool-manuals/preview-quality"
        return httpx.Response(
            200,
            json=envelope(
                {
                    "ok": True,
                    "errors": [],
                    "warnings": [],
                    "quality": {
                        "overall_score": 0,
                        "score": 91,
                        "grade": "F",
                        "publishable": False,
                        "keyword_coverage_estimate": 0,
                        "keyword_coverage": 44,
                        "issues": [],
                        "improvement_suggestions": [],
                    },
                }
            ),
        )

    with build_client(handler) as client:
        report = client.preview_quality_score(tool_manual)

    assert report.overall_score == 0
    assert report.keyword_coverage_estimate == 0


def test_retry_and_api_error_capture_status_code_and_trace_id() -> None:
    attempts = {"count": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        attempts["count"] += 1
        if attempts["count"] == 1:
            return httpx.Response(503, headers={"Retry-After": "0"})
        return httpx.Response(
            409,
            json={
                "error": {
                    "code": "CONFLICT",
                    "message": "Listing already exists.",
                    "details": {"capability_key": "price-compare-helper"},
                },
                "meta": {"trace_id": "trc_conflict", "request_id": "req_conflict"},
            },
        )

    with build_client(handler) as client:
        try:
            client.get_listing("lst_conflict")
        except SiglumeAPIError as exc:
            error = exc
        else:
            raise AssertionError("Expected SiglumeAPIError to be raised.")

    assert attempts["count"] == 2
    assert error.status_code == 409
    assert error.error_code == "CONFLICT"
    assert error.trace_id == "trc_conflict"
    assert error.details["capability_key"] == "price-compare-helper"


def test_list_agents_without_query_returns_personal_agent_singleton() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/me/agent"
        return httpx.Response(
            200,
            json=envelope(
                {
                    "agent_id": "agt_owner_demo",
                    "agent_type": "personal",
                    "name": "Owner Demo",
                    "avatar_url": "/avatars/owner-demo.png",
                    "description": "Owner-managed marketplace agent.",
                    "status": "active",
                    "capabilities": {"marketplace": True},
                    "settings": {"paused": False},
                }
            ),
        )

    with build_client(handler) as client:
        agents = client.list_agents()

    assert len(agents) == 1
    assert agents[0].agent_id == "agt_owner_demo"
    assert agents[0].capabilities["marketplace"] is True
    assert agents[0].settings["paused"] is False


def test_list_agents_with_query_and_get_agent_parse_search_and_profile_shapes() -> None:
    search_calls: list[dict[str, str | None]] = []

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/search/agents":
            assert request.url.params["query"] == "budget"
            search_calls.append(
                {
                    "cursor": request.url.params.get("cursor"),
                    "limit": request.url.params.get("limit"),
                }
            )
            if request.url.params.get("cursor") == "next_agents":
                return httpx.Response(
                    200,
                    json=envelope(
                        {
                            "items": [
                                {
                                    "agent_id": "agt_budget_helper",
                                    "name": "Budget Helper",
                                    "avatar_url": "/avatars/budget-helper.png",
                                    "description": "Tracks cautious purchasing rules.",
                                    "expertise": ["budgeting"],
                                    "post_count": 1,
                                    "reply_count": 0,
                                }
                            ],
                            "next_cursor": None,
                        }
                    ),
                )
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "items": [
                            {
                                "agent_id": "agt_budget_demo",
                                "name": "Budget Demo",
                                "avatar_url": "/avatars/budget-demo.png",
                                "description": "Focuses on budget-safe travel purchases.",
                                "expertise": ["travel", "budgeting"],
                                "post_count": 3,
                                "reply_count": 1,
                            }
                        ],
                        "next_cursor": "next_agents",
                    }
                ),
            )
        if request.url.path == "/v1/agents/agt_budget_demo/profile":
            return httpx.Response(
                200,
                json=envelope(
                    {
                        "agent_id": "agt_budget_demo",
                        "name": "Budget Demo",
                        "avatar_url": "/avatars/budget-demo.png",
                        "description": "Focuses on budget-safe travel purchases.",
                        "agent_type": "personal",
                        "expertise": ["travel", "budgeting"],
                        "style": "careful",
                        "paused": False,
                        "manifesto_text": "Prefer clear budgets and explicit approvals.",
                        "plan": {"tier": "pro"},
                        "reputation": {"score": 0.92},
                        "post_count": 3,
                        "reply_count": 1,
                        "items": [{"content_id": "cnt_demo_1", "title": "Travel safety checklist"}],
                        "next_cursor": None,
                    }
                ),
            )
        raise AssertionError(f"Unexpected request: {request.method} {request.url}")

    with build_client(handler) as client:
        agents = client.list_agents(query="budget", limit=5)
        agent = client.get_agent("agt_budget_demo")

    assert [item.agent_id for item in agents] == ["agt_budget_demo", "agt_budget_helper"]
    assert agents[0].expertise == ["travel", "budgeting"]
    assert agent.manifesto_text == "Prefer clear budgets and explicit approvals."
    assert agent.plan["tier"] == "pro"
    assert agent.items[0]["content_id"] == "cnt_demo_1"
    assert search_calls == [
        {"cursor": None, "limit": "5"},
        {"cursor": "next_agents", "limit": "4"},
    ]


def test_update_agent_charter_maps_charter_text_into_goals_payload() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/charter"
        assert request.method == "PUT"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload["goals"]["charter_text"] == "Prefer capped spend and explicit approval for unusual purchases."
        assert payload["role"] == "buyer"
        assert payload["success_metrics"]["approval_rate_floor"] == 0.8
        assert "wait_for_completion" not in payload
        return httpx.Response(
            200,
            json=envelope(
                {
                    "charter_id": "chr_demo_2",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "version": 2,
                    "active": True,
                    "role": "buyer",
                    "goals": {"charter_text": payload["goals"]["charter_text"]},
                    "target_profile": {},
                    "qualification_criteria": {},
                    "success_metrics": payload["success_metrics"],
                    "constraints": {},
                }
            ),
        )

    with build_client(handler) as client:
        charter = client.update_agent_charter(
            "agt_owner_demo",
            "Prefer capped spend and explicit approval for unusual purchases.",
            role="buyer",
            success_metrics={"approval_rate_floor": 0.8},
            wait_for_completion=True,
        )

    assert charter.charter_id == "chr_demo_2"
    assert charter.charter_text == "Prefer capped spend and explicit approval for unusual purchases."
    assert charter.success_metrics["approval_rate_floor"] == 0.8


def test_update_approval_policy_sanitizes_server_managed_fields() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/approval-policy"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload == {
            "auto_approve_below": {"JPY": 3000},
            "always_require_approval_for": ["travel.booking"],
            "approval_ttl_minutes": 720,
            "structured_only": True,
        }
        return httpx.Response(
            200,
            json=envelope(
                {
                    "approval_policy_id": "apl_demo_2",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "version": 2,
                    "active": True,
                    "auto_approve_below": {"JPY": 3000},
                    "always_require_approval_for": ["travel.booking"],
                    "deny_if": {},
                    "approval_ttl_minutes": 720,
                    "structured_only": True,
                    "merchant_allowlist": [],
                    "merchant_denylist": [],
                    "category_allowlist": [],
                    "category_denylist": [],
                    "risk_policy": {},
                }
            ),
        )

    with build_client(handler) as client:
        policy = client.update_approval_policy(
            "agt_owner_demo",
            {
                "approval_policy_id": "apl_ignore_me",
                "version": 999,
                "auto_approve_below": {"JPY": 3000},
                "always_require_approval_for": ["travel.booking"],
                "approval_ttl_minutes": 720,
                "structured_only": True,
            },
            wait_for_completion=True,
        )

    assert policy.approval_policy_id == "apl_demo_2"
    assert policy.auto_approve_below["JPY"] == 3000
    assert policy.default_requires_approval is True
    assert policy.approval_ttl_minutes == 720


def test_update_budget_policy_sanitizes_server_managed_fields() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/budget"
        payload = json.loads(request.content.decode("utf-8"))
        assert payload == {
            "currency": "JPY",
            "period_limit_minor": 50000,
            "per_order_limit_minor": 12000,
            "auto_approve_below_minor": 3000,
            "metadata": {"source": "sdk-test"},
        }
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_demo_2",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "currency": "JPY",
                    "period_start": "2026-04-01T00:00:00Z",
                    "period_end": "2026-05-01T00:00:00Z",
                    "period_limit_minor": 50000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "per_order_limit_minor": 12000,
                    "auto_approve_below_minor": 3000,
                    "limits": {
                        "period_limit": 50000,
                        "per_order_limit": 12000,
                        "auto_approve_below": 3000,
                    },
                    "metadata": {"source": "sdk-test"},
                }
            ),
        )

    with build_client(handler) as client:
        budget = client.update_budget_policy(
            "agt_owner_demo",
            {
                "budget_id": "bdg_ignore_me",
                "currency": "JPY",
                "period_limit_minor": 50000,
                "per_order_limit_minor": 12000,
                "auto_approve_below_minor": 3000,
                "metadata": {"source": "sdk-test"},
            },
            wait_for_completion=True,
        )

    assert budget.budget_id == "bdg_demo_2"
    assert budget.period_limit_minor == 50000
    assert budget.limits["per_order_limit"] == 12000


def test_update_budget_policy_forwards_null_period_dates_to_clear_them() -> None:
    """period_start / period_end are nullable — sending None must clear the boundary on the server."""

    captured_payload: dict[str, Any] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/owner/agents/agt_owner_demo/budget"
        captured_payload.update(json.loads(request.content.decode("utf-8")))
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_clear_dates",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "currency": "JPY",
                    "period_start": None,
                    "period_end": None,
                    "period_limit_minor": 50000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "limits": {},
                    "metadata": {},
                }
            ),
        )

    with build_client(handler) as client:
        client.update_budget_policy(
            "agt_owner_demo",
            {"period_start": None, "period_end": None},
        )

    assert captured_payload == {"period_start": None, "period_end": None}


def test_update_budget_policy_still_strips_nulls_for_non_nullable_fields() -> None:
    """Non-nullable fields like currency must still be filtered when None is passed."""

    captured_payload: dict[str, Any] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured_payload.update(json.loads(request.content.decode("utf-8")))
        return httpx.Response(
            200,
            json=envelope(
                {
                    "budget_id": "bdg_strip_nonnullable",
                    "agent_id": "agt_owner_demo",
                    "principal_user_id": "usr_owner_demo",
                    "currency": "USD",
                    "period_limit_minor": 1000,
                    "spent_minor": 0,
                    "reserved_minor": 0,
                    "limits": {},
                    "metadata": {},
                }
            ),
        )

    with build_client(handler) as client:
        client.update_budget_policy(
            "agt_owner_demo",
            {"currency": None, "period_limit_minor": 1000},
        )

    assert captured_payload == {"period_limit_minor": 1000}


def test_update_budget_policy_rejects_payload_with_only_filtered_fields() -> None:
    """If the only field provided is a non-nullable None, the whole call should still error."""

    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError("handler should not be called")

    with build_client(handler) as client:
        try:
            client.update_budget_policy("agt_owner_demo", {"currency": None})
        except SiglumeClientError:
            return
    raise AssertionError("Expected SiglumeClientError when the only field is a stripped None")
