"""Package wrapper that preserves the legacy flat-module public API."""
from __future__ import annotations

from importlib import util
from pathlib import Path
import sys
from types import ModuleType


_LEGACY_MODULE_NAME = "_siglume_api_sdk_legacy"
_LEGACY_MODULE_PATH = Path(__file__).resolve().parent.parent / "siglume_api_sdk.py"
_LEGACY_PUBLIC_EXPORTS = [
    "AppAdapter",
    "AppCategory",
    "AppManifest",
    "AppTestHarness",
    "ApprovalMode",
    "ApprovalRequestHint",
    "ConnectedAccountRef",
    "Environment",
    "ExecutionArtifact",
    "ExecutionContext",
    "ExecutionKind",
    "ExecutionResult",
    "HealthCheckResult",
    "PermissionClass",
    "PriceModel",
    "ReceiptRef",
    "SettlementMode",
    "SideEffectRecord",
    "StubProvider",
    "ToolManual",
    "ToolManualIssue",
    "ToolManualPermissionClass",
    "ToolManualQualityReport",
    "validate_tool_manual",
]


def _load_legacy_module() -> ModuleType:
    existing = sys.modules.get(_LEGACY_MODULE_NAME)
    if existing is not None:
        return existing
    spec = util.spec_from_file_location(_LEGACY_MODULE_NAME, _LEGACY_MODULE_PATH)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load legacy SDK module from {_LEGACY_MODULE_PATH}")
    module = util.module_from_spec(spec)
    sys.modules[_LEGACY_MODULE_NAME] = module
    spec.loader.exec_module(module)
    return module


_legacy = _load_legacy_module()

for _name in _LEGACY_PUBLIC_EXPORTS:
    globals()[_name] = getattr(_legacy, _name)

from .client import (  # noqa: E402, F401
    AccessGrantRecord,
    AccountAlert,
    AccountContentDeleteResult,
    AccountContentPostResult,
    AccountDigest,
    AccountDigestItem,
    AccountDigestSummary,
    AccountFeedbackSubmission,
    AccountPlan,
    AccountPlanCancellation,
    AccountPreferences,
    AccountWatchlist,
    AgentCharter,
    AgentRecord,
    AgentThreadRecord,
    AgentTopicSubscription,
    AppListingRecord,
    ApprovalPolicy,
    AutoRegistrationReceipt,
    BillingPortalLink,
    BudgetPolicy,
    CapabilityBindingRecord,
    ConnectedAccountRecord,
    CursorPage,
    DEFAULT_SIGLUME_API_BASE,
    DeveloperPortalSummary,
    Dispute,
    DisputeResponse,
    DisputeStatus,
    EnvelopeMeta,
    FavoriteAgent,
    FavoriteAgentMutation,
    GrantBindingResult,
    InstalledToolBindingPolicyRecord,
    InstalledToolConnectionReadiness,
    InstalledToolExecutionRecord,
    InstalledToolPolicyUpdateResult,
    InstalledToolReceiptRecord,
    InstalledToolReceiptStepRecord,
    InstalledToolRecord,
    MarketNeedRecord,
    NetworkClaimRecord,
    NetworkContentDetail,
    NetworkContentSummary,
    NetworkEvidenceRecord,
    NetworkRepliesPage,
    OperationExecution,
    PlanCheckoutSession,
    PlanWeb3Mandate,
    RegistrationConfirmation,
    RegistrationQuality,
    Refund,
    RefundReason,
    RefundStatus,
    SandboxSession,
    SiglumeAPIError,
    SiglumeClient,
    SiglumeClientError,
    SiglumeNotFoundError,
    SupportCaseRecord,
    UsageEventRecord,
    WorksCategoryRecord,
    WorksOwnerDashboard,
    WorksOwnerDashboardAgent,
    WorksOwnerDashboardOrder,
    WorksOwnerDashboardPitch,
    WorksOwnerDashboardStats,
    WorksPosterDashboard,
    WorksPosterDashboardJob,
    WorksPosterDashboardOrder,
    WorksPosterDashboardStats,
    WorksRegistrationRecord,
)
from .operations import OperationMetadata  # noqa: E402, F401
from .buyer import (  # noqa: E402, F401
    CapabilityListing,
    SiglumeBuyerClient,
    SiglumeExperimentalError,
    SiglumeExperimentalWarning,
    Subscription,
)
from .diff import (  # noqa: E402, F401
    BreakingChange,
    Change,
    ChangeLevel,
    diff_manifest,
    diff_tool_manual,
)
from .exporters import (  # noqa: E402, F401
    ToolSchemaExport,
    to_anthropic_tool,
    to_mcp_tool,
    to_openai_function,
    to_openai_responses_tool,
)
from .metering import MeterClient, MeterRecordResult, UsageRecord  # noqa: E402, F401
from .refunds import RefundClient  # noqa: E402, F401
from .testing import Recorder, RecordMode  # noqa: E402, F401
from .tool_manual_assist import (  # noqa: E402, F401
    AnthropicProvider,
    LLMProvider,
    OpenAIProvider,
    SiglumeAssistError,
    ToolManualAssistAttempt,
    ToolManualAssistMetadata,
    ToolManualAssistResult,
    draft_tool_manual,
    fill_tool_manual_gaps,
    load_tool_manual_draft_prompt,
)
from .tool_manual_grader import score_tool_manual_offline, score_tool_manual_remote  # noqa: E402, F401
from .web3 import (  # noqa: E402, F401
    CrossCurrencyQuote,
    EmbeddedWalletCharge,
    PolygonMandate,
    SettlementReceipt,
    parse_cross_currency_quote,
    parse_embedded_wallet_charge,
    parse_polygon_mandate,
    parse_settlement_receipt,
    simulate_embedded_wallet_charge,
    simulate_polygon_mandate,
)
from .webhooks import (  # noqa: E402, F401
    CapabilityDelistedEvent,
    CapabilityPublishedEvent,
    DEFAULT_WEBHOOK_TOLERANCE_SECONDS,
    ExecutionCompletedEvent,
    ExecutionFailedEvent,
    InMemoryWebhookDedupe,
    PaymentDisputedEvent,
    PaymentFailedEvent,
    PaymentSucceededEvent,
    QueuedWebhookEvent,
    RefundIssuedEvent,
    SiglumeWebhookError,
    SiglumeWebhookPayloadError,
    SiglumeWebhookReplayError,
    SiglumeWebhookSignatureError,
    SubscriptionCancelledEvent,
    SubscriptionCreatedEvent,
    SubscriptionPausedEvent,
    SubscriptionReinstatedEvent,
    SubscriptionRenewedEvent,
    WebhookDeliveryRecord,
    WebhookDispatchResult,
    WebhookHandler,
    WebhookSignatureVerification,
    WebhookSubscriptionRecord,
    WEBHOOK_EVENT_ID_HEADER,
    WEBHOOK_EVENT_TYPE_HEADER,
    WEBHOOK_EVENT_TYPES,
    WEBHOOK_SIGNATURE_HEADER,
    build_webhook_signature_header,
    compute_webhook_signature,
    parse_queued_webhook_event,
    parse_webhook_delivery,
    parse_webhook_event,
    parse_webhook_subscription,
    verify_webhook_signature,
)

__all__ = sorted(
    set(
        _LEGACY_PUBLIC_EXPORTS
        + [
            "AccessGrantRecord",
            "AccountAlert",
            "AccountContentDeleteResult",
            "AccountContentPostResult",
            "AccountDigest",
            "AccountDigestItem",
            "AccountDigestSummary",
            "AccountFeedbackSubmission",
            "AccountPlan",
            "AccountPlanCancellation",
            "AccountPreferences",
            "AccountWatchlist",
            "AgentCharter",
            "AgentRecord",
            "AgentThreadRecord",
            "AgentTopicSubscription",
            "AppListingRecord",
            "ApprovalPolicy",
            "AutoRegistrationReceipt",
            "BillingPortalLink",
            "BudgetPolicy",
            "CapabilityBindingRecord",
            "CapabilityListing",
            "Change",
            "ChangeLevel",
            "ConnectedAccountRecord",
            "CursorPage",
            "DEFAULT_SIGLUME_API_BASE",
            "DeveloperPortalSummary",
            "Dispute",
            "DisputeResponse",
            "DisputeStatus",
            "EnvelopeMeta",
            "FavoriteAgent",
            "FavoriteAgentMutation",
            "GrantBindingResult",
            "InstalledToolBindingPolicyRecord",
            "InstalledToolConnectionReadiness",
            "InstalledToolExecutionRecord",
            "InstalledToolPolicyUpdateResult",
            "InstalledToolReceiptRecord",
            "InstalledToolReceiptStepRecord",
            "InstalledToolRecord",
            "MarketNeedRecord",
            "NetworkClaimRecord",
            "NetworkContentDetail",
            "NetworkContentSummary",
            "NetworkEvidenceRecord",
            "NetworkRepliesPage",
            "OperationExecution",
            "OperationMetadata",
            "PlanCheckoutSession",
            "PlanWeb3Mandate",
            "BreakingChange",
            "RegistrationConfirmation",
            "RegistrationQuality",
            "Refund",
            "RefundClient",
            "RefundReason",
            "RefundStatus",
            "SandboxSession",
            "MeterClient",
            "MeterRecordResult",
            "CrossCurrencyQuote",
            "EmbeddedWalletCharge",
            "PolygonMandate",
            "SiglumeAPIError",
            "SiglumeAssistError",
            "SiglumeBuyerClient",
            "SiglumeClient",
            "SiglumeClientError",
            "SiglumeExperimentalError",
            "SiglumeExperimentalWarning",
            "SiglumeNotFoundError",
            "SettlementReceipt",
            "Subscription",
            "SupportCaseRecord",
            "ToolSchemaExport",
            "UsageEventRecord",
            "UsageRecord",
            "WorksCategoryRecord",
            "WorksOwnerDashboard",
            "WorksOwnerDashboardAgent",
            "WorksOwnerDashboardOrder",
            "WorksOwnerDashboardPitch",
            "WorksOwnerDashboardStats",
            "WorksPosterDashboard",
            "WorksPosterDashboardJob",
            "WorksPosterDashboardOrder",
            "WorksPosterDashboardStats",
            "WorksRegistrationRecord",
            "AnthropicProvider",
            "LLMProvider",
            "OpenAIProvider",
            "RecordMode",
            "Recorder",
            "diff_manifest",
            "diff_tool_manual",
            "to_anthropic_tool",
            "to_mcp_tool",
            "to_openai_function",
            "to_openai_responses_tool",
            "ToolManualAssistAttempt",
            "ToolManualAssistMetadata",
            "ToolManualAssistResult",
            "draft_tool_manual",
            "fill_tool_manual_gaps",
            "load_tool_manual_draft_prompt",
            "parse_cross_currency_quote",
            "parse_embedded_wallet_charge",
            "parse_polygon_mandate",
            "parse_settlement_receipt",
            "score_tool_manual_offline",
            "score_tool_manual_remote",
            "simulate_embedded_wallet_charge",
            "simulate_polygon_mandate",
            "CapabilityDelistedEvent",
            "CapabilityPublishedEvent",
            "DEFAULT_WEBHOOK_TOLERANCE_SECONDS",
            "ExecutionCompletedEvent",
            "ExecutionFailedEvent",
            "InMemoryWebhookDedupe",
            "PaymentDisputedEvent",
            "PaymentFailedEvent",
            "PaymentSucceededEvent",
            "QueuedWebhookEvent",
            "RefundIssuedEvent",
            "SiglumeWebhookError",
            "SiglumeWebhookPayloadError",
            "SiglumeWebhookReplayError",
            "SiglumeWebhookSignatureError",
            "SubscriptionCancelledEvent",
            "SubscriptionCreatedEvent",
            "SubscriptionPausedEvent",
            "SubscriptionReinstatedEvent",
            "SubscriptionRenewedEvent",
            "WebhookDeliveryRecord",
            "WebhookDispatchResult",
            "WebhookHandler",
            "WebhookSignatureVerification",
            "WebhookSubscriptionRecord",
            "WEBHOOK_EVENT_ID_HEADER",
            "WEBHOOK_EVENT_TYPE_HEADER",
            "WEBHOOK_EVENT_TYPES",
            "WEBHOOK_SIGNATURE_HEADER",
            "build_webhook_signature_header",
            "compute_webhook_signature",
            "parse_queued_webhook_event",
            "parse_webhook_delivery",
            "parse_webhook_event",
            "parse_webhook_subscription",
            "verify_webhook_signature",
        ]
    )
)
